[2025-06-27T02:22:29.674+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-06-27T02:22:29.779+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: WF_MAIN_END_MONTH.run_hop_pipeline scheduled__2025-05-01T14:00:00+00:00 [queued]>
[2025-06-27T02:22:29.818+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: WF_MAIN_END_MONTH.run_hop_pipeline scheduled__2025-05-01T14:00:00+00:00 [queued]>
[2025-06-27T02:22:29.819+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-06-27T02:22:29.885+0000] {taskinstance.py:2330} INFO - Executing <Task(DockerOperator): run_hop_pipeline> on 2025-05-01 14:00:00+00:00
[2025-06-27T02:22:29.902+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=64) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-06-27T02:22:29.917+0000] {standard_task_runner.py:63} INFO - Started process 71 to run task
[2025-06-27T02:22:29.918+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'WF_MAIN_END_MONTH', 'run_hop_pipeline', 'scheduled__2025-05-01T14:00:00+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/apache-hop-dag-wf-main-end-month.py', '--cfg-path', '/tmp/tmp95wxw1u_']
[2025-06-27T02:22:29.929+0000] {standard_task_runner.py:91} INFO - Job 3: Subtask run_hop_pipeline
[2025-06-27T02:22:30.400+0000] {task_command.py:426} INFO - Running <TaskInstance: WF_MAIN_END_MONTH.run_hop_pipeline scheduled__2025-05-01T14:00:00+00:00 [running]> on host 0b41c6d28592
[2025-06-27T02:22:30.780+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='WF_MAIN_END_MONTH' AIRFLOW_CTX_TASK_ID='run_hop_pipeline' AIRFLOW_CTX_EXECUTION_DATE='2025-05-01T14:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-05-01T14:00:00+00:00'
[2025-06-27T02:22:30.782+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-06-27T02:22:30.974+0000] {docker.py:493} INFO - Pulling docker image apache/hop:latest
[2025-06-27T02:22:33.734+0000] {docker.py:507} INFO - latest: Pulling from apache/hop
[2025-06-27T02:22:38.098+0000] {docker.py:507} INFO - 19f1029c3f10: Pulling fs layer
[2025-06-27T02:22:38.099+0000] {docker.py:507} INFO - 9b6bc2cf1037: Pulling fs layer
[2025-06-27T02:22:38.099+0000] {docker.py:507} INFO - eb2b48b7cabe: Pulling fs layer
[2025-06-27T02:22:38.100+0000] {docker.py:507} INFO - d4d2578e96cd: Pulling fs layer
[2025-06-27T02:22:38.101+0000] {docker.py:507} INFO - 4f4fb700ef54: Pulling fs layer
[2025-06-27T02:22:38.101+0000] {docker.py:507} INFO - f18232174bc9: Pulling fs layer
[2025-06-27T02:22:38.102+0000] {docker.py:507} INFO - bf26d906d0f5: Pulling fs layer
[2025-06-27T02:22:38.103+0000] {docker.py:507} INFO - f488a4dddc73: Pulling fs layer
[2025-06-27T02:22:38.106+0000] {docker.py:507} INFO - 4f4fb700ef54: Already exists
[2025-06-27T02:22:38.108+0000] {docker.py:507} INFO - 4f4fb700ef54: Pull complete
[2025-06-27T02:22:38.305+0000] {docker.py:507} INFO - 9b6bc2cf1037: Downloading
[2025-06-27T02:22:38.717+0000] {docker.py:507} INFO - f488a4dddc73: Downloading
[2025-06-27T02:22:38.719+0000] {docker.py:507} INFO - eb2b48b7cabe: Downloading
[2025-06-27T02:22:38.720+0000] {docker.py:507} INFO - d4d2578e96cd: Downloading
[2025-06-27T02:22:39.129+0000] {docker.py:507} INFO - bf26d906d0f5: Downloading
[2025-06-27T02:22:39.334+0000] {docker.py:507} INFO - f18232174bc9: Downloading
[2025-06-27T02:22:39.335+0000] {docker.py:507} INFO - 19f1029c3f10: Downloading
[2025-06-27T02:22:47.948+0000] {docker.py:507} INFO - 9b6bc2cf1037: Download complete
[2025-06-27T02:22:48.183+0000] {docker.py:507} INFO - eb2b48b7cabe: Download complete
[2025-06-27T02:22:48.223+0000] {docker.py:507} INFO - d4d2578e96cd: Download complete
[2025-06-27T02:22:49.043+0000] {docker.py:507} INFO - f18232174bc9: Download complete
[2025-06-27T02:22:49.044+0000] {docker.py:507} INFO - bf26d906d0f5: Download complete
[2025-06-27T02:22:49.088+0000] {docker.py:507} INFO - f18232174bc9: Extracting
[2025-06-27T02:22:52.561+0000] {docker.py:507} INFO - 19f1029c3f10: Download complete
[2025-06-27T02:22:54.000+0000] {docker.py:507} INFO - f18232174bc9: Pull complete
[2025-06-27T02:23:00.905+0000] {docker.py:507} INFO - d4d2578e96cd: Extracting
[2025-06-27T02:23:06.516+0000] {docker.py:507} INFO - d4d2578e96cd: Pull complete
[2025-06-27T02:23:09.839+0000] {docker.py:507} INFO - 19f1029c3f10: Extracting
[2025-06-27T02:23:24.600+0000] {docker.py:507} INFO - 19f1029c3f10: Pull complete
[2025-06-27T02:23:30.306+0000] {docker.py:507} INFO - bf26d906d0f5: Extracting
[2025-06-27T02:23:31.105+0000] {docker.py:507} INFO - bf26d906d0f5: Pull complete
[2025-06-27T02:23:40.696+0000] {docker.py:507} INFO - f488a4dddc73: Download complete
[2025-06-27T02:23:40.704+0000] {docker.py:507} INFO - f488a4dddc73: Extracting
[2025-06-27T02:24:20.394+0000] {docker.py:507} INFO - f488a4dddc73: Pull complete
[2025-06-27T02:24:20.531+0000] {docker.py:507} INFO - 9b6bc2cf1037: Pull complete
[2025-06-27T02:24:20.691+0000] {docker.py:507} INFO - eb2b48b7cabe: Pull complete
[2025-06-27T02:24:21.116+0000] {docker.py:502} INFO - Digest: sha256:950a95da3332a2782706665b58adeed820689d87e0ca5b54df59bc995b2d955e
[2025-06-27T02:24:21.117+0000] {docker.py:502} INFO - Status: Downloaded newer image for apache/hop:latest
[2025-06-27T02:24:21.144+0000] {docker.py:366} INFO - Starting docker container from image apache/hop:latest
[2025-06-27T02:24:21.320+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-06-27T02:24:21.326+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/docker/api/client.py", line 265, in _raise_for_status
    response.raise_for_status()
  File "/home/airflow/.local/lib/python3.12/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: http+docker://localhost/v1.50/containers/create

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 509, in execute
    return self._run_image()
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 371, in _run_image
    return self._run_image_with_mounts([*self.mounts, tmp_mount], add_tmp_variable=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 398, in _run_image_with_mounts
    self.container = self.cli.create_container(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/docker/api/container.py", line 439, in create_container
    return self.create_container_from_config(config, name, platform)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/docker/api/container.py", line 456, in create_container_from_config
    return self._result(res, True)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/docker/api/client.py", line 271, in _result
    self._raise_for_status(response)
  File "/home/airflow/.local/lib/python3.12/site-packages/docker/api/client.py", line 267, in _raise_for_status
    raise create_api_error_from_http_exception(e) from e
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/docker/errors.py", line 39, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation) from e
docker.errors.APIError: 400 Client Error for http+docker://localhost/v1.50/containers/create: Bad Request ("invalid mount config for type "bind": bind source path does not exist: /mnt/data/ProyectoSmart/ProyectoSmartMed")
[2025-06-27T02:24:21.396+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=WF_MAIN_END_MONTH, task_id=run_hop_pipeline, run_id=scheduled__2025-05-01T14:00:00+00:00, execution_date=20250501T140000, start_date=20250627T022229, end_date=20250627T022421
[2025-06-27T02:24:21.467+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 3 for task run_hop_pipeline (400 Client Error for http+docker://localhost/v1.50/containers/create: Bad Request ("invalid mount config for type "bind": bind source path does not exist: /mnt/data/ProyectoSmart/ProyectoSmartMed"); 71)
[2025-06-27T02:24:21.595+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-06-27T02:24:21.735+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-06-27T02:24:21.745+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2025-06-27T03:49:08.535+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-06-27T03:49:08.666+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: WF_MAIN_END_MONTH.run_hop_pipeline scheduled__2025-05-01T14:00:00+00:00 [queued]>
[2025-06-27T03:49:08.696+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: WF_MAIN_END_MONTH.run_hop_pipeline scheduled__2025-05-01T14:00:00+00:00 [queued]>
[2025-06-27T03:49:08.697+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-06-27T03:49:08.735+0000] {taskinstance.py:2330} INFO - Executing <Task(DockerOperator): run_hop_pipeline> on 2025-05-01 14:00:00+00:00
[2025-06-27T03:49:08.754+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=68) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-06-27T03:49:08.759+0000] {standard_task_runner.py:63} INFO - Started process 71 to run task
[2025-06-27T03:49:08.760+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'WF_MAIN_END_MONTH', 'run_hop_pipeline', 'scheduled__2025-05-01T14:00:00+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/apache-hop-dag-wf-main-end-month.py', '--cfg-path', '/tmp/tmpvxi2ywek']
[2025-06-27T03:49:08.763+0000] {standard_task_runner.py:91} INFO - Job 4: Subtask run_hop_pipeline
[2025-06-27T03:49:10.625+0000] {task_command.py:426} INFO - Running <TaskInstance: WF_MAIN_END_MONTH.run_hop_pipeline scheduled__2025-05-01T14:00:00+00:00 [running]> on host 24f72b4a1d8f
[2025-06-27T03:49:11.042+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='WF_MAIN_END_MONTH' AIRFLOW_CTX_TASK_ID='run_hop_pipeline' AIRFLOW_CTX_EXECUTION_DATE='2025-05-01T14:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-05-01T14:00:00+00:00'
[2025-06-27T03:49:11.044+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-06-27T03:49:11.187+0000] {docker.py:366} INFO - Starting docker container from image apache/hop:latest
[2025-06-27T03:49:11.745+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-06-27T03:49:11.746+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/docker/api/client.py", line 265, in _raise_for_status
    response.raise_for_status()
  File "/home/airflow/.local/lib/python3.12/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: http+docker://localhost/v1.50/containers/create

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 509, in execute
    return self._run_image()
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 371, in _run_image
    return self._run_image_with_mounts([*self.mounts, tmp_mount], add_tmp_variable=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 398, in _run_image_with_mounts
    self.container = self.cli.create_container(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/docker/api/container.py", line 439, in create_container
    return self.create_container_from_config(config, name, platform)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/docker/api/container.py", line 456, in create_container_from_config
    return self._result(res, True)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/docker/api/client.py", line 271, in _result
    self._raise_for_status(response)
  File "/home/airflow/.local/lib/python3.12/site-packages/docker/api/client.py", line 267, in _raise_for_status
    raise create_api_error_from_http_exception(e) from e
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/docker/errors.py", line 39, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation) from e
docker.errors.APIError: 400 Client Error for http+docker://localhost/v1.50/containers/create: Bad Request ("invalid mount config for type "bind": bind source path does not exist: /mnt/data/ProyectoSmart/ProyectoSmartMed")
[2025-06-27T03:49:11.762+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=WF_MAIN_END_MONTH, task_id=run_hop_pipeline, run_id=scheduled__2025-05-01T14:00:00+00:00, execution_date=20250501T140000, start_date=20250627T034908, end_date=20250627T034911
[2025-06-27T03:49:12.014+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 4 for task run_hop_pipeline (400 Client Error for http+docker://localhost/v1.50/containers/create: Bad Request ("invalid mount config for type "bind": bind source path does not exist: /mnt/data/ProyectoSmart/ProyectoSmartMed"); 71)
[2025-06-27T03:49:12.306+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-06-27T03:49:12.340+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-06-27T03:49:12.439+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2025-06-27T04:12:46.649+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-06-27T04:12:46.700+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: WF_MAIN_END_MONTH.run_hop_pipeline scheduled__2025-05-01T14:00:00+00:00 [queued]>
[2025-06-27T04:12:46.719+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: WF_MAIN_END_MONTH.run_hop_pipeline scheduled__2025-05-01T14:00:00+00:00 [queued]>
[2025-06-27T04:12:46.720+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2025-06-27T04:12:46.756+0000] {taskinstance.py:2888} INFO - Executing <Task(DockerOperator): run_hop_pipeline> on 2025-05-01 14:00:00+00:00
[2025-06-27T04:12:46.774+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=66) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-06-27T04:12:46.779+0000] {standard_task_runner.py:72} INFO - Started process 74 to run task
[2025-06-27T04:12:46.788+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'WF_MAIN_END_MONTH', 'run_hop_pipeline', 'scheduled__2025-05-01T14:00:00+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/apache-hop-dag-wf-main-end-month.py', '--cfg-path', '/tmp/tmpvhevx1dw']
[2025-06-27T04:12:46.791+0000] {standard_task_runner.py:105} INFO - Job 6: Subtask run_hop_pipeline
[2025-06-27T04:12:47.699+0000] {task_command.py:467} INFO - Running <TaskInstance: WF_MAIN_END_MONTH.run_hop_pipeline scheduled__2025-05-01T14:00:00+00:00 [running]> on host 9f6303ed7827
[2025-06-27T04:12:48.296+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='WF_MAIN_END_MONTH' AIRFLOW_CTX_TASK_ID='run_hop_pipeline' AIRFLOW_CTX_EXECUTION_DATE='2025-05-01T14:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-05-01T14:00:00+00:00'
[2025-06-27T04:12:48.299+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-06-27T04:12:48.398+0000] {docker.py:496} INFO - ::group::Pulling docker image apache/hop:latest
[2025-06-27T04:12:51.914+0000] {docker.py:510} INFO - latest: Pulling from apache/hop
[2025-06-27T04:12:58.084+0000] {docker.py:510} INFO - bf26d906d0f5: Pulling fs layer
[2025-06-27T04:12:58.086+0000] {docker.py:510} INFO - 4f4fb700ef54: Pulling fs layer
[2025-06-27T04:12:58.087+0000] {docker.py:510} INFO - f488a4dddc73: Pulling fs layer
[2025-06-27T04:12:58.088+0000] {docker.py:510} INFO - 9b6bc2cf1037: Pulling fs layer
[2025-06-27T04:12:58.089+0000] {docker.py:510} INFO - eb2b48b7cabe: Pulling fs layer
[2025-06-27T04:12:58.092+0000] {docker.py:510} INFO - d4d2578e96cd: Pulling fs layer
[2025-06-27T04:12:58.093+0000] {docker.py:510} INFO - f18232174bc9: Pulling fs layer
[2025-06-27T04:12:58.094+0000] {docker.py:510} INFO - 19f1029c3f10: Pulling fs layer
[2025-06-27T04:12:58.164+0000] {docker.py:510} INFO - 4f4fb700ef54: Already exists
[2025-06-27T04:12:58.176+0000] {docker.py:510} INFO - 4f4fb700ef54: Pull complete
[2025-06-27T04:12:58.766+0000] {docker.py:510} INFO - f18232174bc9: Downloading
[2025-06-27T04:12:59.028+0000] {docker.py:510} INFO - eb2b48b7cabe: Downloading
[2025-06-27T04:12:59.081+0000] {docker.py:510} INFO - 9b6bc2cf1037: Downloading
[2025-06-27T04:12:59.091+0000] {docker.py:510} INFO - d4d2578e96cd: Downloading
[2025-06-27T04:12:59.156+0000] {docker.py:510} INFO - bf26d906d0f5: Downloading
[2025-06-27T04:12:59.398+0000] {docker.py:510} INFO - 19f1029c3f10: Downloading
[2025-06-27T04:12:59.492+0000] {docker.py:510} INFO - f488a4dddc73: Downloading
[2025-06-27T04:13:15.940+0000] {job.py:229} INFO - Heartbeat recovered after 13.79 seconds
[2025-06-27T04:13:20.268+0000] {docker.py:510} INFO - eb2b48b7cabe: Download complete
[2025-06-27T04:13:20.283+0000] {docker.py:510} INFO - f18232174bc9: Download complete
[2025-06-27T04:13:20.300+0000] {docker.py:510} INFO - f18232174bc9: Extracting
[2025-06-27T04:13:21.199+0000] {docker.py:510} INFO - 9b6bc2cf1037: Download complete
[2025-06-27T04:13:21.436+0000] {job.py:229} INFO - Heartbeat recovered after 14.03 seconds
[2025-06-27T04:13:21.512+0000] {docker.py:510} INFO - d4d2578e96cd: Download complete
[2025-06-27T04:13:21.760+0000] {docker.py:510} INFO - bf26d906d0f5: Download complete
[2025-06-27T04:13:25.490+0000] {docker.py:510} INFO - 19f1029c3f10: Download complete
[2025-06-27T04:13:28.915+0000] {docker.py:510} INFO - f18232174bc9: Pull complete
[2025-06-27T04:13:34.576+0000] {docker.py:510} INFO - d4d2578e96cd: Extracting
[2025-06-27T04:13:36.853+0000] {docker.py:510} INFO - d4d2578e96cd: Pull complete
[2025-06-27T04:13:41.442+0000] {docker.py:510} INFO - 19f1029c3f10: Extracting
[2025-06-27T04:14:13.235+0000] {docker.py:510} INFO - 19f1029c3f10: Pull complete
[2025-06-27T04:14:25.508+0000] {job.py:229} INFO - Heartbeat recovered after 11.05 seconds
[2025-06-27T04:14:30.711+0000] {job.py:229} INFO - Heartbeat recovered after 11.11 seconds
[2025-06-27T04:14:31.827+0000] {docker.py:510} INFO - bf26d906d0f5: Extracting
[2025-06-27T04:14:33.360+0000] {docker.py:510} INFO - bf26d906d0f5: Pull complete
[2025-06-27T04:14:41.799+0000] {docker.py:510} INFO - f488a4dddc73: Download complete
[2025-06-27T04:14:41.812+0000] {docker.py:510} INFO - f488a4dddc73: Extracting
[2025-06-27T04:16:07.269+0000] {docker.py:510} INFO - f488a4dddc73: Pull complete
[2025-06-27T04:16:07.377+0000] {docker.py:510} INFO - 9b6bc2cf1037: Pull complete
[2025-06-27T04:16:07.461+0000] {docker.py:510} INFO - eb2b48b7cabe: Extracting
[2025-06-27T04:16:07.562+0000] {docker.py:510} INFO - eb2b48b7cabe: Pull complete
[2025-06-27T04:16:07.723+0000] {docker.py:505} INFO - Digest: sha256:950a95da3332a2782706665b58adeed820689d87e0ca5b54df59bc995b2d955e
[2025-06-27T04:16:07.724+0000] {docker.py:505} INFO - Status: Downloaded newer image for apache/hop:latest
[2025-06-27T04:16:07.745+0000] {docker.py:512} INFO - ::endgroup::
[2025-06-27T04:16:07.748+0000] {docker.py:367} INFO - Starting docker container from image apache/hop:latest
[2025-06-27T04:16:07.912+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/docker/api/client.py", line 275, in _raise_for_status
    response.raise_for_status()
  File "/home/airflow/.local/lib/python3.12/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: http+docker://localhost/v1.50/containers/create

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 513, in execute
    return self._run_image()
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 372, in _run_image
    return self._run_image_with_mounts([*self.mounts, tmp_mount], add_tmp_variable=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 399, in _run_image_with_mounts
    self.container = self.cli.create_container(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/docker/api/container.py", line 440, in create_container
    return self.create_container_from_config(config, name, platform)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/docker/api/container.py", line 457, in create_container_from_config
    return self._result(res, True)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/docker/api/client.py", line 281, in _result
    self._raise_for_status(response)
  File "/home/airflow/.local/lib/python3.12/site-packages/docker/api/client.py", line 277, in _raise_for_status
    raise create_api_error_from_http_exception(e) from e
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/docker/errors.py", line 39, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation) from e
docker.errors.APIError: 400 Client Error for http+docker://localhost/v1.50/containers/create: Bad Request ("invalid mount config for type "bind": bind source path does not exist: /mnt/data/ProyectoSmart/ProyectoSmartMed")
[2025-06-27T04:16:07.977+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=WF_MAIN_END_MONTH, task_id=run_hop_pipeline, run_id=scheduled__2025-05-01T14:00:00+00:00, execution_date=20250501T140000, start_date=20250627T041246, end_date=20250627T041607
[2025-06-27T04:16:08.073+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-06-27T04:16:08.075+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 6 for task run_hop_pipeline (400 Client Error for http+docker://localhost/v1.50/containers/create: Bad Request ("invalid mount config for type "bind": bind source path does not exist: /mnt/data/ProyectoSmart/ProyectoSmartMed"); 74)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/docker/api/client.py", line 275, in _raise_for_status
    response.raise_for_status()
  File "/home/airflow/.local/lib/python3.12/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: http+docker://localhost/v1.50/containers/create

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 513, in execute
    return self._run_image()
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 372, in _run_image
    return self._run_image_with_mounts([*self.mounts, tmp_mount], add_tmp_variable=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 399, in _run_image_with_mounts
    self.container = self.cli.create_container(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/docker/api/container.py", line 440, in create_container
    return self.create_container_from_config(config, name, platform)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/docker/api/container.py", line 457, in create_container_from_config
    return self._result(res, True)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/docker/api/client.py", line 281, in _result
    self._raise_for_status(response)
  File "/home/airflow/.local/lib/python3.12/site-packages/docker/api/client.py", line 277, in _raise_for_status
    raise create_api_error_from_http_exception(e) from e
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/docker/errors.py", line 39, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation) from e
docker.errors.APIError: 400 Client Error for http+docker://localhost/v1.50/containers/create: Bad Request ("invalid mount config for type "bind": bind source path does not exist: /mnt/data/ProyectoSmart/ProyectoSmartMed")
[2025-06-27T04:16:08.137+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-06-27T04:16:08.215+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-06-27T04:16:08.226+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-06-27T04:48:28.535+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-06-27T04:48:28.587+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: WF_MAIN_END_MONTH.run_hop_pipeline scheduled__2025-05-01T14:00:00+00:00 [queued]>
[2025-06-27T04:48:28.605+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: WF_MAIN_END_MONTH.run_hop_pipeline scheduled__2025-05-01T14:00:00+00:00 [queued]>
[2025-06-27T04:48:28.607+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2025-06-27T04:48:28.641+0000] {taskinstance.py:2888} INFO - Executing <Task(DockerOperator): run_hop_pipeline> on 2025-05-01 14:00:00+00:00
[2025-06-27T04:48:28.670+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=66) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-06-27T04:48:28.681+0000] {standard_task_runner.py:72} INFO - Started process 74 to run task
[2025-06-27T04:48:28.692+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'WF_MAIN_END_MONTH', 'run_hop_pipeline', 'scheduled__2025-05-01T14:00:00+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/apache-hop-dag-wf-main-end-month.py', '--cfg-path', '/tmp/tmp0fs5nrs0']
[2025-06-27T04:48:28.695+0000] {standard_task_runner.py:105} INFO - Job 6: Subtask run_hop_pipeline
[2025-06-27T04:48:28.896+0000] {task_command.py:467} INFO - Running <TaskInstance: WF_MAIN_END_MONTH.run_hop_pipeline scheduled__2025-05-01T14:00:00+00:00 [running]> on host 11460eb2799d
[2025-06-27T04:48:29.253+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='WF_MAIN_END_MONTH' AIRFLOW_CTX_TASK_ID='run_hop_pipeline' AIRFLOW_CTX_EXECUTION_DATE='2025-05-01T14:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-05-01T14:00:00+00:00'
[2025-06-27T04:48:29.256+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-06-27T04:48:29.618+0000] {docker.py:367} INFO - Starting docker container from image apache/hop:latest
[2025-06-27T04:48:29.721+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/docker/api/client.py", line 275, in _raise_for_status
    response.raise_for_status()
  File "/home/airflow/.local/lib/python3.12/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: http+docker://localhost/v1.50/containers/create

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 513, in execute
    return self._run_image()
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 372, in _run_image
    return self._run_image_with_mounts([*self.mounts, tmp_mount], add_tmp_variable=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 399, in _run_image_with_mounts
    self.container = self.cli.create_container(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/docker/api/container.py", line 440, in create_container
    return self.create_container_from_config(config, name, platform)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/docker/api/container.py", line 457, in create_container_from_config
    return self._result(res, True)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/docker/api/client.py", line 281, in _result
    self._raise_for_status(response)
  File "/home/airflow/.local/lib/python3.12/site-packages/docker/api/client.py", line 277, in _raise_for_status
    raise create_api_error_from_http_exception(e) from e
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/docker/errors.py", line 39, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation) from e
docker.errors.APIError: 400 Client Error for http+docker://localhost/v1.50/containers/create: Bad Request ("invalid mount config for type "bind": bind source path does not exist: /mnt/data/ProyectoSmart/ProyectoSmartMed")
[2025-06-27T04:48:29.793+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=WF_MAIN_END_MONTH, task_id=run_hop_pipeline, run_id=scheduled__2025-05-01T14:00:00+00:00, execution_date=20250501T140000, start_date=20250627T044828, end_date=20250627T044829
[2025-06-27T04:48:29.838+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-06-27T04:48:29.844+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 6 for task run_hop_pipeline (400 Client Error for http+docker://localhost/v1.50/containers/create: Bad Request ("invalid mount config for type "bind": bind source path does not exist: /mnt/data/ProyectoSmart/ProyectoSmartMed"); 74)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/docker/api/client.py", line 275, in _raise_for_status
    response.raise_for_status()
  File "/home/airflow/.local/lib/python3.12/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: http+docker://localhost/v1.50/containers/create

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 513, in execute
    return self._run_image()
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 372, in _run_image
    return self._run_image_with_mounts([*self.mounts, tmp_mount], add_tmp_variable=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 399, in _run_image_with_mounts
    self.container = self.cli.create_container(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/docker/api/container.py", line 440, in create_container
    return self.create_container_from_config(config, name, platform)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/docker/api/container.py", line 457, in create_container_from_config
    return self._result(res, True)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/docker/api/client.py", line 281, in _result
    self._raise_for_status(response)
  File "/home/airflow/.local/lib/python3.12/site-packages/docker/api/client.py", line 277, in _raise_for_status
    raise create_api_error_from_http_exception(e) from e
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/docker/errors.py", line 39, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation) from e
docker.errors.APIError: 400 Client Error for http+docker://localhost/v1.50/containers/create: Bad Request ("invalid mount config for type "bind": bind source path does not exist: /mnt/data/ProyectoSmart/ProyectoSmartMed")
[2025-06-27T04:48:29.914+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-06-27T04:48:29.956+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-06-27T04:48:29.961+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-06-27T04:59:17.366+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-06-27T04:59:17.420+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: WF_MAIN_END_MONTH.run_hop_pipeline scheduled__2025-05-01T14:00:00+00:00 [queued]>
[2025-06-27T04:59:17.443+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: WF_MAIN_END_MONTH.run_hop_pipeline scheduled__2025-05-01T14:00:00+00:00 [queued]>
[2025-06-27T04:59:17.444+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-06-27T04:59:17.479+0000] {taskinstance.py:2330} INFO - Executing <Task(DockerOperator): run_hop_pipeline> on 2025-05-01 14:00:00+00:00
[2025-06-27T04:59:17.496+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=68) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-06-27T04:59:17.500+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'WF_MAIN_END_MONTH', 'run_hop_pipeline', 'scheduled__2025-05-01T14:00:00+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/apache-hop-dag-wf-main-end-month.py', '--cfg-path', '/tmp/tmpc7s2hp9p']
[2025-06-27T04:59:17.502+0000] {standard_task_runner.py:63} INFO - Started process 72 to run task
[2025-06-27T04:59:17.503+0000] {standard_task_runner.py:91} INFO - Job 6: Subtask run_hop_pipeline
[2025-06-27T04:59:17.713+0000] {task_command.py:426} INFO - Running <TaskInstance: WF_MAIN_END_MONTH.run_hop_pipeline scheduled__2025-05-01T14:00:00+00:00 [running]> on host 4c575de26931
[2025-06-27T04:59:17.951+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='WF_MAIN_END_MONTH' AIRFLOW_CTX_TASK_ID='run_hop_pipeline' AIRFLOW_CTX_EXECUTION_DATE='2025-05-01T14:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-05-01T14:00:00+00:00'
[2025-06-27T04:59:17.955+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-06-27T04:59:18.247+0000] {docker.py:366} INFO - Starting docker container from image apache/hop:latest
[2025-06-27T04:59:18.301+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-06-27T04:59:18.304+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/docker/api/client.py", line 265, in _raise_for_status
    response.raise_for_status()
  File "/home/airflow/.local/lib/python3.12/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: http+docker://localhost/v1.50/containers/create

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 509, in execute
    return self._run_image()
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 371, in _run_image
    return self._run_image_with_mounts([*self.mounts, tmp_mount], add_tmp_variable=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 398, in _run_image_with_mounts
    self.container = self.cli.create_container(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/docker/api/container.py", line 439, in create_container
    return self.create_container_from_config(config, name, platform)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/docker/api/container.py", line 456, in create_container_from_config
    return self._result(res, True)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/docker/api/client.py", line 271, in _result
    self._raise_for_status(response)
  File "/home/airflow/.local/lib/python3.12/site-packages/docker/api/client.py", line 267, in _raise_for_status
    raise create_api_error_from_http_exception(e) from e
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/docker/errors.py", line 39, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation) from e
docker.errors.APIError: 400 Client Error for http+docker://localhost/v1.50/containers/create: Bad Request ("invalid mount config for type "bind": bind source path does not exist: /mnt/data/ProyectoSmart/ProyectoSmartMed")
[2025-06-27T04:59:18.341+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=WF_MAIN_END_MONTH, task_id=run_hop_pipeline, run_id=scheduled__2025-05-01T14:00:00+00:00, execution_date=20250501T140000, start_date=20250627T045917, end_date=20250627T045918
[2025-06-27T04:59:18.383+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 6 for task run_hop_pipeline (400 Client Error for http+docker://localhost/v1.50/containers/create: Bad Request ("invalid mount config for type "bind": bind source path does not exist: /mnt/data/ProyectoSmart/ProyectoSmartMed"); 72)
[2025-06-27T04:59:18.420+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-06-27T04:59:18.522+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-06-27T04:59:18.532+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2025-06-27T05:41:02.257+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-06-27T05:41:02.339+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: WF_MAIN_END_MONTH.run_hop_pipeline scheduled__2025-05-01T14:00:00+00:00 [queued]>
[2025-06-27T05:41:02.358+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: WF_MAIN_END_MONTH.run_hop_pipeline scheduled__2025-05-01T14:00:00+00:00 [queued]>
[2025-06-27T05:41:02.359+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-06-27T05:41:02.409+0000] {taskinstance.py:2330} INFO - Executing <Task(DockerOperator): run_hop_pipeline> on 2025-05-01 14:00:00+00:00
[2025-06-27T05:41:02.431+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=67) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-06-27T05:41:02.439+0000] {standard_task_runner.py:63} INFO - Started process 72 to run task
[2025-06-27T05:41:02.441+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'WF_MAIN_END_MONTH', 'run_hop_pipeline', 'scheduled__2025-05-01T14:00:00+00:00', '--job-id', '7', '--raw', '--subdir', 'DAGS_FOLDER/apache-hop-dag-wf-main-end-month.py', '--cfg-path', '/tmp/tmp3kglpp3g']
[2025-06-27T05:41:02.443+0000] {standard_task_runner.py:91} INFO - Job 7: Subtask run_hop_pipeline
[2025-06-27T05:41:02.712+0000] {task_command.py:426} INFO - Running <TaskInstance: WF_MAIN_END_MONTH.run_hop_pipeline scheduled__2025-05-01T14:00:00+00:00 [running]> on host 760ca3d6cb03
[2025-06-27T05:41:02.977+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='WF_MAIN_END_MONTH' AIRFLOW_CTX_TASK_ID='run_hop_pipeline' AIRFLOW_CTX_EXECUTION_DATE='2025-05-01T14:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-05-01T14:00:00+00:00'
[2025-06-27T05:41:02.981+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-06-27T05:41:03.236+0000] {docker.py:366} INFO - Starting docker container from image apache/hop:latest
[2025-06-27T05:41:03.295+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-06-27T05:41:03.298+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/docker/api/client.py", line 265, in _raise_for_status
    response.raise_for_status()
  File "/home/airflow/.local/lib/python3.12/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: http+docker://localhost/v1.50/containers/create

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 509, in execute
    return self._run_image()
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 371, in _run_image
    return self._run_image_with_mounts([*self.mounts, tmp_mount], add_tmp_variable=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 398, in _run_image_with_mounts
    self.container = self.cli.create_container(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/docker/api/container.py", line 439, in create_container
    return self.create_container_from_config(config, name, platform)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/docker/api/container.py", line 456, in create_container_from_config
    return self._result(res, True)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/docker/api/client.py", line 271, in _result
    self._raise_for_status(response)
  File "/home/airflow/.local/lib/python3.12/site-packages/docker/api/client.py", line 267, in _raise_for_status
    raise create_api_error_from_http_exception(e) from e
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/docker/errors.py", line 39, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation) from e
docker.errors.APIError: 400 Client Error for http+docker://localhost/v1.50/containers/create: Bad Request ("invalid mount config for type "bind": bind source path does not exist: /opt/airflow/ProyectoSmartMed")
[2025-06-27T05:41:03.339+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=WF_MAIN_END_MONTH, task_id=run_hop_pipeline, run_id=scheduled__2025-05-01T14:00:00+00:00, execution_date=20250501T140000, start_date=20250627T054102, end_date=20250627T054103
[2025-06-27T05:41:03.380+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 7 for task run_hop_pipeline (400 Client Error for http+docker://localhost/v1.50/containers/create: Bad Request ("invalid mount config for type "bind": bind source path does not exist: /opt/airflow/ProyectoSmartMed"); 72)
[2025-06-27T05:41:03.471+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-06-27T05:41:03.531+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-06-27T05:41:03.534+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2025-06-27T06:06:12.629+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-06-27T06:06:12.680+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: WF_MAIN_END_MONTH.run_hop_pipeline scheduled__2025-05-01T14:00:00+00:00 [queued]>
[2025-06-27T06:06:12.697+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: WF_MAIN_END_MONTH.run_hop_pipeline scheduled__2025-05-01T14:00:00+00:00 [queued]>
[2025-06-27T06:06:12.698+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-06-27T06:06:12.728+0000] {taskinstance.py:2330} INFO - Executing <Task(DockerOperator): run_hop_pipeline> on 2025-05-01 14:00:00+00:00
[2025-06-27T06:06:12.739+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=63) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-06-27T06:06:12.744+0000] {standard_task_runner.py:63} INFO - Started process 65 to run task
[2025-06-27T06:06:12.743+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'WF_MAIN_END_MONTH', 'run_hop_pipeline', 'scheduled__2025-05-01T14:00:00+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/apache-hop-dag-wf-main-end-month.py', '--cfg-path', '/tmp/tmpxs0xsjk6']
[2025-06-27T06:06:12.746+0000] {standard_task_runner.py:91} INFO - Job 3: Subtask run_hop_pipeline
[2025-06-27T06:06:12.923+0000] {task_command.py:426} INFO - Running <TaskInstance: WF_MAIN_END_MONTH.run_hop_pipeline scheduled__2025-05-01T14:00:00+00:00 [running]> on host 71fa9c4e435e
[2025-06-27T06:06:13.065+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='WF_MAIN_END_MONTH' AIRFLOW_CTX_TASK_ID='run_hop_pipeline' AIRFLOW_CTX_EXECUTION_DATE='2025-05-01T14:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-05-01T14:00:00+00:00'
[2025-06-27T06:06:13.066+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-06-27T06:06:13.235+0000] {docker.py:366} INFO - Starting docker container from image apache/hop:latest
[2025-06-27T06:06:13.253+0000] {docker.py:374} WARNING - Using remote engine or docker-in-docker and mounting temporary volume from host is not supported. Falling back to `mount_tmp_dir=False` mode. You can set `mount_tmp_dir` parameter to False to disable mounting and remove the warning
[2025-06-27T06:06:16.705+0000] {docker.py:436} INFO - 2025/06/27 06:06:16 - Running the entrypoint script with PID 7
[2025-06-27T06:06:16.708+0000] {docker.py:436} INFO - 2025/06/27 06:06:16 - The project folder for ProyectoSmartMed is set to: /files
[2025-06-27T06:06:16.712+0000] {docker.py:436} INFO - 2025/06/27 06:06:16 - The specified project folder exists
[2025-06-27T06:06:16.715+0000] {docker.py:436} INFO - 2025/06/27 06:06:16 - Registering project ProyectoSmartMed in the Hop container configuration
[2025-06-27T06:06:16.717+0000] {docker.py:436} INFO - 2025/06/27 06:06:16 - /opt/hop/hop-conf.sh --project=ProyectoSmartMed --project-create --project-home='/files' --project-config-file='project-config.json'
[2025-06-27T06:11:13.215+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-06-27T06:11:13.262+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: WF_MAIN_END_MONTH.run_hop_pipeline scheduled__2025-05-01T14:00:00+00:00 [queued]>
[2025-06-27T06:11:13.278+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: WF_MAIN_END_MONTH.run_hop_pipeline scheduled__2025-05-01T14:00:00+00:00 [queued]>
[2025-06-27T06:11:13.279+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-06-27T06:11:13.309+0000] {taskinstance.py:2330} INFO - Executing <Task(DockerOperator): run_hop_pipeline> on 2025-05-01 14:00:00+00:00
[2025-06-27T06:11:13.328+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=69) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-06-27T06:11:13.334+0000] {standard_task_runner.py:63} INFO - Started process 71 to run task
[2025-06-27T06:11:13.332+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'WF_MAIN_END_MONTH', 'run_hop_pipeline', 'scheduled__2025-05-01T14:00:00+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/apache-hop-dag-wf-main-end-month.py', '--cfg-path', '/tmp/tmp7f4ct_p0']
[2025-06-27T06:11:13.335+0000] {standard_task_runner.py:91} INFO - Job 6: Subtask run_hop_pipeline
[2025-06-27T06:11:13.511+0000] {task_command.py:426} INFO - Running <TaskInstance: WF_MAIN_END_MONTH.run_hop_pipeline scheduled__2025-05-01T14:00:00+00:00 [running]> on host 9bc187bed6c8
[2025-06-27T06:11:13.698+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='WF_MAIN_END_MONTH' AIRFLOW_CTX_TASK_ID='run_hop_pipeline' AIRFLOW_CTX_EXECUTION_DATE='2025-05-01T14:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-05-01T14:00:00+00:00'
[2025-06-27T06:11:13.701+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-06-27T06:11:13.956+0000] {docker.py:366} INFO - Starting docker container from image apache/hop:latest
[2025-06-27T06:11:14.017+0000] {docker.py:374} WARNING - Using remote engine or docker-in-docker and mounting temporary volume from host is not supported. Falling back to `mount_tmp_dir=False` mode. You can set `mount_tmp_dir` parameter to False to disable mounting and remove the warning
[2025-06-27T06:11:15.641+0000] {docker.py:436} INFO - 2025/06/27 06:11:15 - Running the entrypoint script with PID 7
[2025-06-27T06:11:15.643+0000] {docker.py:436} INFO - 2025/06/27 06:11:15 - The project folder for ProyectoSmartMed is set to: /files
[2025-06-27T06:11:15.645+0000] {docker.py:436} INFO - 2025/06/27 06:11:15 - The specified project folder exists
[2025-06-27T06:11:15.648+0000] {docker.py:436} INFO - 2025/06/27 06:11:15 - Registering project ProyectoSmartMed in the Hop container configuration
[2025-06-27T06:11:15.728+0000] {docker.py:436} INFO - 2025/06/27 06:11:15 - /opt/hop/hop-conf.sh --project=ProyectoSmartMed --project-create --project-home='/files' --project-config-file='project-config.json'
[2025-06-27T06:46:18.215+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-06-27T06:46:18.282+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: WF_MAIN_END_MONTH.run_hop_pipeline scheduled__2025-05-01T14:00:00+00:00 [queued]>
[2025-06-27T06:46:18.302+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: WF_MAIN_END_MONTH.run_hop_pipeline scheduled__2025-05-01T14:00:00+00:00 [queued]>
[2025-06-27T06:46:18.303+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-06-27T06:46:18.349+0000] {taskinstance.py:2330} INFO - Executing <Task(DockerOperator): run_hop_pipeline> on 2025-05-01 14:00:00+00:00
[2025-06-27T06:46:18.374+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=65) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-06-27T06:46:18.377+0000] {standard_task_runner.py:63} INFO - Started process 73 to run task
[2025-06-27T06:46:18.385+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'WF_MAIN_END_MONTH', 'run_hop_pipeline', 'scheduled__2025-05-01T14:00:00+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/apache-hop-dag-wf-main-end-month.py', '--cfg-path', '/tmp/tmp92pim69p']
[2025-06-27T06:46:18.390+0000] {standard_task_runner.py:91} INFO - Job 6: Subtask run_hop_pipeline
[2025-06-27T06:46:18.568+0000] {task_command.py:426} INFO - Running <TaskInstance: WF_MAIN_END_MONTH.run_hop_pipeline scheduled__2025-05-01T14:00:00+00:00 [running]> on host eefc0d82eb46
[2025-06-27T06:46:18.817+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='WF_MAIN_END_MONTH' AIRFLOW_CTX_TASK_ID='run_hop_pipeline' AIRFLOW_CTX_EXECUTION_DATE='2025-05-01T14:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-05-01T14:00:00+00:00'
[2025-06-27T06:46:18.821+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-06-27T06:46:19.041+0000] {docker.py:366} INFO - Starting docker container from image apache/hop:latest
[2025-06-27T06:46:19.063+0000] {docker.py:374} WARNING - Using remote engine or docker-in-docker and mounting temporary volume from host is not supported. Falling back to `mount_tmp_dir=False` mode. You can set `mount_tmp_dir` parameter to False to disable mounting and remove the warning
[2025-06-27T06:46:20.264+0000] {docker.py:436} INFO - 2025/06/27 06:46:20 - The project folder for ProyectoSmartMed is set to: /files
[2025-06-27T06:46:20.270+0000] {docker.py:436} INFO - 2025/06/27 06:46:20 - Running the entrypoint script with PID 6
[2025-06-27T06:46:20.276+0000] {docker.py:436} INFO - 2025/06/27 06:46:20 - The specified project folder exists
[2025-06-27T06:46:20.285+0000] {docker.py:436} INFO - 2025/06/27 06:46:20 - Registering project ProyectoSmartMed in the Hop container configuration
2025/06/27 06:46:20 - /opt/hop/hop-conf.sh --project=ProyectoSmartMed --project-create --project-home='/files' --project-config-file='project-config.json'
[2025-06-27T06:47:26.886+0000] {docker.py:436} INFO - Creating project 'ProyectoSmartMed'
[2025-06-27T06:47:27.793+0000] {docker.py:436} INFO - Project 'ProyectoSmartMed' was created for home folder : /files
[2025-06-27T06:47:27.963+0000] {docker.py:436} INFO - Configuration file for project 'ProyectoSmartMed' was saved to : file:/files/project-config.json
[2025-06-27T06:47:28.191+0000] {docker.py:436} INFO - 2025/06/27 06:47:28 - Not creating an environment in the container
[2025-06-27T06:47:28.194+0000] {docker.py:436} INFO - 2025/06/27 06:47:28 - Running a single hop workflow / pipeline (${PROJECT_HOME}/workflows/WF_MAIN_END_MONTH.hwf)
[2025-06-27T06:47:53.001+0000] {docker.py:436} INFO - 2025/06/27 06:47:52 - HopRun - Enabling project 'ProyectoSmartMed'
[2025-06-27T06:47:53.672+0000] {docker.py:436} INFO - 2025/06/27 06:47:53 - HopRun - Starting workflow: /files/workflows/WF_MAIN_END_MONTH.hwf
[2025-06-27T06:47:56.613+0000] {docker.py:436} INFO - 2025/06/27 06:47:56 - WF_MAIN_END_MONTH - Start of workflow execution
[2025-06-27T06:47:56.761+0000] {docker.py:436} INFO - 2025/06/27 06:47:56 - WF_MAIN_END_MONTH - Starting action [filename_end_month.hwf]
[2025-06-27T06:47:57.467+0000] {docker.py:436} INFO - 2025/06/27 06:47:57 - filename_end_month - Start of workflow execution
[2025-06-27T06:47:57.497+0000] {docker.py:436} INFO - 2025/06/27 06:47:57 - filename_end_month - Starting action [PRUEBA_END_MONTH.hpl]
[2025-06-27T06:47:57.621+0000] {docker.py:436} INFO - 2025/06/27 06:47:57 - PRUEBA_END_MONTH.hpl - Using run configuration [local]
[2025-06-27T06:47:57.679+0000] {docker.py:436} INFO - 2025/06/27 06:47:57 - PRUEBA_END_MONTH - Executing this pipeline using the Local Pipeline Engine with run configuration 'local'
[2025-06-27T06:47:57.693+0000] {docker.py:436} INFO - 2025/06/27 06:47:57 - PRUEBA_END_MONTH - Execution started for pipeline [PRUEBA_END_MONTH]
[2025-06-27T06:48:02.797+0000] {docker.py:436} INFO - 2025/06/27 06:48:02 - Set variables.0 - Setting project variables...
[2025-06-27T06:48:02.799+0000] {docker.py:436} INFO - 2025/06/27 06:48:02 - Table input.0 - Finished reading query, closing connection.
2025/06/27 06:48:02 - Set variables.0 - Set variable lastDate to value [2025-05-01]
[2025-06-27T06:48:02.801+0000] {docker.py:436} INFO - 2025/06/27 06:48:02 - Set variables 2.0 - Setting project variables...
2025/06/27 06:48:02 - Set variables 2.0 - Set variable endDate to value [2025-05-31]
[2025-06-27T06:48:02.821+0000] {docker.py:436} INFO - 2025/06/27 06:48:02 - Set variables.0 - Finished after 1 rows.
[2025-06-27T06:48:02.825+0000] {docker.py:436} INFO - 2025/06/27 06:48:02 - Set variables.0 - Finished processing (I=0, O=0, R=1, W=1, U=0, E=0)
[2025-06-27T06:48:02.832+0000] {docker.py:436} INFO - 2025/06/27 06:48:02 - Dummy (do nothing).0 - Finished processing (I=0, O=0, R=1, W=1, U=0, E=0)
[2025-06-27T06:48:02.846+0000] {docker.py:436} INFO - 2025/06/27 06:48:02 - Dummy (do nothing) 2.0 - Finished processing (I=0, O=0, R=1, W=1, U=0, E=0)
[2025-06-27T06:48:02.863+0000] {docker.py:436} INFO - 2025/06/27 06:48:02 - Set variables 2.0 - Finished after 1 rows.
2025/06/27 06:48:02 - Set variables 2.0 - Finished processing (I=0, O=0, R=1, W=1, U=0, E=0)
[2025-06-27T06:48:02.916+0000] {docker.py:436} INFO - 2025/06/27 06:48:02 - Table input.0 - Finished processing (I=1, O=0, R=0, W=1, U=0, E=0)
[2025-06-27T06:48:02.929+0000] {docker.py:436} INFO - 2025/06/27 06:48:02 - PRUEBA_END_MONTH - Pipeline duration : 5.239 seconds [  5.238" ]
[2025-06-27T06:48:03.076+0000] {docker.py:436} INFO - 2025/06/27 06:48:03 - PRUEBA_END_MONTH - Execution finished on a local pipeline engine with run configuration 'local'
[2025-06-27T06:48:03.100+0000] {docker.py:436} INFO - 2025/06/27 06:48:03 - filename_end_month - Starting action [End Repeat]
[2025-06-27T06:48:03.173+0000] {docker.py:436} INFO - 2025/06/27 06:48:03 - filename_end_month - Finished action [End Repeat] (result=[true])
[2025-06-27T06:48:03.176+0000] {docker.py:436} INFO - 2025/06/27 06:48:03 - filename_end_month - Finished action [PRUEBA_END_MONTH.hpl] (result=[true])
[2025-06-27T06:48:03.179+0000] {docker.py:436} INFO - 2025/06/27 06:48:03 - filename_end_month - Workflow execution finished
[2025-06-27T06:48:03.240+0000] {docker.py:436} INFO - 2025/06/27 06:48:03 - filename_end_month - Workflow duration : 6.259 seconds [  6.259" ]
[2025-06-27T06:48:03.255+0000] {docker.py:436} INFO - 2025/06/27 06:48:03 - WF_MAIN_END_MONTH - Starting action [WF_CARGA_FUENTES.hwf]
[2025-06-27T06:48:04.277+0000] {docker.py:436} INFO - 2025/06/27 06:48:04 - WF_CARGA_FUENTES - Start of workflow execution
[2025-06-27T06:48:04.339+0000] {docker.py:436} INFO - 2025/06/27 06:48:04 - WF_CARGA_FUENTES - Starting action [CARGA_MODELOS.hpl]
[2025-06-27T06:48:04.519+0000] {docker.py:436} INFO - 2025/06/27 06:48:04 - CARGA_MODELOS.hpl - Using run configuration [local]
[2025-06-27T06:48:04.656+0000] {docker.py:436} INFO - 2025/06/27 06:48:04 - CARGA_MODELOS - Executing this pipeline using the Local Pipeline Engine with run configuration 'local'
[2025-06-27T06:48:04.669+0000] {docker.py:436} INFO - 2025/06/27 06:48:04 - CARGA_MODELOS - Execution started for pipeline [CARGA_MODELOS]
[2025-06-27T06:48:09.226+0000] {docker.py:436} INFO - 2025/06/27 06:48:09 - as_meter_model.0 - Finished reading query, closing connection.
[2025-06-27T06:48:09.228+0000] {docker.py:436} INFO - 2025/06/27 06:48:09 - as_meter_model.0 - Finished processing (I=111, O=0, R=0, W=111, U=0, E=0)
[2025-06-27T06:48:09.278+0000] {docker.py:436} INFO - 2025/06/27 06:48:09 - modelos_csv.0 - Finished processing (I=0, O=112, R=111, W=111, U=0, E=0)
[2025-06-27T06:48:09.279+0000] {docker.py:436} INFO - 2025/06/27 06:48:09 - CARGA_MODELOS - Pipeline duration : 4.627 seconds [  4.626" ]
[2025-06-27T06:48:09.314+0000] {docker.py:436} INFO - 2025/06/27 06:48:09 - CARGA_MODELOS - Execution finished on a local pipeline engine with run configuration 'local'
[2025-06-27T06:48:09.319+0000] {docker.py:436} INFO - 2025/06/27 06:48:09 - WF_CARGA_FUENTES - Starting action [End Repeat]
[2025-06-27T06:48:09.332+0000] {docker.py:436} INFO - 2025/06/27 06:48:09 - WF_CARGA_FUENTES - Finished action [End Repeat] (result=[true])
[2025-06-27T06:48:09.333+0000] {docker.py:436} INFO - 2025/06/27 06:48:09 - WF_CARGA_FUENTES - Finished action [CARGA_MODELOS.hpl] (result=[true])
[2025-06-27T06:48:09.334+0000] {docker.py:436} INFO - 2025/06/27 06:48:09 - WF_CARGA_FUENTES - Starting action [CARGA_MEDIDORES.hpl]
[2025-06-27T06:48:09.370+0000] {docker.py:436} INFO - 2025/06/27 06:48:09 - CARGA_MEDIDORES.hpl - Using run configuration [local]
[2025-06-27T06:48:09.394+0000] {docker.py:436} INFO - 2025/06/27 06:48:09 - CARGA_MEDIDORES - Executing this pipeline using the Local Pipeline Engine with run configuration 'local'
[2025-06-27T06:48:09.396+0000] {docker.py:436} INFO - 2025/06/27 06:48:09 - CARGA_MEDIDORES - Execution started for pipeline [CARGA_MEDIDORES]
[2025-06-27T06:48:14.533+0000] {docker.py:436} INFO - 2025/06/27 06:48:14 - as_meter.0 - Finished reading query, closing connection.
[2025-06-27T06:48:14.534+0000] {docker.py:436} INFO - 2025/06/27 06:48:14 - as_meter.0 - Finished processing (I=32434, O=0, R=0, W=32434, U=0, E=0)
[2025-06-27T06:48:15.174+0000] {docker.py:436} INFO - 2025/06/27 06:48:15 - medidores.0 - Finished processing (I=0, O=32435, R=32434, W=32434, U=0, E=0)
[2025-06-27T06:48:15.175+0000] {docker.py:436} INFO - 2025/06/27 06:48:15 - CARGA_MEDIDORES - Pipeline duration : 5.78 seconds [  5.780" ]
[2025-06-27T06:48:15.203+0000] {docker.py:436} INFO - 2025/06/27 06:48:15 - CARGA_MEDIDORES - Execution finished on a local pipeline engine with run configuration 'local'
[2025-06-27T06:48:15.205+0000] {docker.py:436} INFO - 2025/06/27 06:48:15 - WF_CARGA_FUENTES - Starting action [End Repeat]
[2025-06-27T06:48:15.214+0000] {docker.py:436} INFO - 2025/06/27 06:48:15 - WF_CARGA_FUENTES - Finished action [End Repeat] (result=[true])
2025/06/27 06:48:15 - WF_CARGA_FUENTES - Finished action [CARGA_MEDIDORES.hpl] (result=[true])
[2025-06-27T06:48:15.215+0000] {docker.py:436} INFO - 2025/06/27 06:48:15 - WF_CARGA_FUENTES - Starting action [CARGA_HECHOS.hpl]
[2025-06-27T06:48:15.268+0000] {docker.py:436} INFO - 2025/06/27 06:48:15 - CARGA_HECHOS.hpl - Using run configuration [local]
[2025-06-27T06:48:15.294+0000] {docker.py:436} INFO - 2025/06/27 06:48:15 - CARGA_HECHOS - Executing this pipeline using the Local Pipeline Engine with run configuration 'local'
[2025-06-27T06:48:15.298+0000] {docker.py:436} INFO - 2025/06/27 06:48:15 - CARGA_HECHOS - Execution started for pipeline [CARGA_HECHOS]
[2025-06-27T07:20:45.942+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-06-27T07:20:46.011+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: WF_MAIN_END_MONTH.run_hop_pipeline scheduled__2025-05-01T14:00:00+00:00 [queued]>
[2025-06-27T07:20:46.034+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: WF_MAIN_END_MONTH.run_hop_pipeline scheduled__2025-05-01T14:00:00+00:00 [queued]>
[2025-06-27T07:20:46.036+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-06-27T07:20:46.112+0000] {taskinstance.py:2330} INFO - Executing <Task(DockerOperator): run_hop_pipeline> on 2025-05-01 14:00:00+00:00
[2025-06-27T07:20:46.166+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=64) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-06-27T07:20:46.164+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'WF_MAIN_END_MONTH', 'run_hop_pipeline', 'scheduled__2025-05-01T14:00:00+00:00', '--job-id', '7', '--raw', '--subdir', 'DAGS_FOLDER/apache-hop-dag-wf-main-end-month.py', '--cfg-path', '/tmp/tmp6gf472lm']
[2025-06-27T07:20:46.173+0000] {standard_task_runner.py:63} INFO - Started process 69 to run task
[2025-06-27T07:20:46.177+0000] {standard_task_runner.py:91} INFO - Job 7: Subtask run_hop_pipeline
[2025-06-27T07:20:46.493+0000] {task_command.py:426} INFO - Running <TaskInstance: WF_MAIN_END_MONTH.run_hop_pipeline scheduled__2025-05-01T14:00:00+00:00 [running]> on host 5e15c4a8eeb7
[2025-06-27T07:20:46.739+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='WF_MAIN_END_MONTH' AIRFLOW_CTX_TASK_ID='run_hop_pipeline' AIRFLOW_CTX_EXECUTION_DATE='2025-05-01T14:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-05-01T14:00:00+00:00'
[2025-06-27T07:20:46.744+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-06-27T07:20:47.001+0000] {docker.py:366} INFO - Starting docker container from image apache/hop:latest
[2025-06-27T07:20:47.076+0000] {docker.py:374} WARNING - Using remote engine or docker-in-docker and mounting temporary volume from host is not supported. Falling back to `mount_tmp_dir=False` mode. You can set `mount_tmp_dir` parameter to False to disable mounting and remove the warning
[2025-06-27T07:20:48.365+0000] {docker.py:436} INFO - 2025/06/27 07:20:48 - Running the entrypoint script with PID 8
[2025-06-27T07:20:48.366+0000] {docker.py:436} INFO - 2025/06/27 07:20:48 - The project folder for ProyectoSmartMed is set to: /files
[2025-06-27T07:20:48.368+0000] {docker.py:436} INFO - 2025/06/27 07:20:48 - The specified project folder exists
[2025-06-27T07:20:48.369+0000] {docker.py:436} INFO - 2025/06/27 07:20:48 - Registering project ProyectoSmartMed in the Hop container configuration
[2025-06-27T07:20:48.370+0000] {docker.py:436} INFO - 2025/06/27 07:20:48 - /opt/hop/hop-conf.sh --project=ProyectoSmartMed --project-create --project-home='/files' --project-config-file='project-config.json'
[2025-06-27T07:22:15.800+0000] {docker.py:436} INFO - Creating project 'ProyectoSmartMed'
[2025-06-27T07:22:16.951+0000] {docker.py:436} INFO - Project 'ProyectoSmartMed' was created for home folder : /files
[2025-06-27T07:22:17.240+0000] {docker.py:436} INFO - Configuration file for project 'ProyectoSmartMed' was saved to : file:/files/project-config.json
[2025-06-27T07:22:17.459+0000] {docker.py:436} INFO - 2025/06/27 07:22:17 - Not creating an environment in the container
[2025-06-27T07:22:17.462+0000] {docker.py:436} INFO - 2025/06/27 07:22:17 - Running a single hop workflow / pipeline (${PROJECT_HOME}/workflows/WF_MAIN_END_MONTH.hwf)
[2025-06-27T07:22:51.983+0000] {docker.py:436} INFO - 2025/06/27 07:22:51 - HopRun - Enabling project 'ProyectoSmartMed'
[2025-06-27T07:22:52.868+0000] {docker.py:436} INFO - 2025/06/27 07:22:52 - HopRun - Starting workflow: /files/workflows/WF_MAIN_END_MONTH.hwf
[2025-06-27T07:22:56.708+0000] {docker.py:436} INFO - 2025/06/27 07:22:56 - WF_MAIN_END_MONTH - Start of workflow execution
[2025-06-27T07:22:57.112+0000] {docker.py:436} INFO - 2025/06/27 07:22:57 - WF_MAIN_END_MONTH - Starting action [filename_end_month.hwf]
[2025-06-27T07:22:57.992+0000] {docker.py:436} INFO - 2025/06/27 07:22:57 - filename_end_month - Start of workflow execution
[2025-06-27T07:22:58.022+0000] {docker.py:436} INFO - 2025/06/27 07:22:58 - filename_end_month - Starting action [PRUEBA_END_MONTH.hpl]
[2025-06-27T07:22:58.202+0000] {docker.py:436} INFO - 2025/06/27 07:22:58 - PRUEBA_END_MONTH.hpl - Using run configuration [local]
[2025-06-27T07:22:58.290+0000] {docker.py:436} INFO - 2025/06/27 07:22:58 - PRUEBA_END_MONTH - Executing this pipeline using the Local Pipeline Engine with run configuration 'local'
[2025-06-27T07:22:58.325+0000] {docker.py:436} INFO - 2025/06/27 07:22:58 - PRUEBA_END_MONTH - Execution started for pipeline [PRUEBA_END_MONTH]
[2025-06-27T07:23:08.999+0000] {docker.py:436} INFO - 2025/06/27 07:23:08 - Table input.0 - ERROR: An error occurred, processing will be stopped: 
2025/06/27 07:23:08 - Table input.0 - Error occurred while trying to connect to the database
2025/06/27 07:23:08 - Table input.0 - 
2025/06/27 07:23:08 - Table input.0 - Error connecting to database: (using class org.postgresql.Driver)
2025/06/27 07:23:08 - Table input.0 - The connection attempt failed.
[2025-06-27T07:23:09.115+0000] {docker.py:436} INFO - 2025/06/27 07:23:09 - Table input.0 - ERROR: Error initializing transform [Table input]
[2025-06-27T07:23:09.119+0000] {docker.py:436} INFO - 2025/06/27 07:23:09 - PRUEBA_END_MONTH - ERROR: Transform [Table input.0] failed to initialize!
[2025-06-27T07:23:09.123+0000] {docker.py:436} INFO - 2025/06/27 07:23:09 - Table input.0 - Finished reading query, closing connection.
[2025-06-27T07:23:09.132+0000] {docker.py:436} INFO - 2025/06/27 07:23:09 - PRUEBA_END_MONTH.hpl - ERROR: Unable to prepare for execution of the pipeline
[2025-06-27T07:23:09.140+0000] {docker.py:436} INFO - 2025/06/27 07:23:09 - PRUEBA_END_MONTH.hpl - ERROR: org.apache.hop.core.exception.HopException: 
2025/06/27 07:23:09 - PRUEBA_END_MONTH.hpl - We failed to initialize at least one transform.  Execution can not begin!
2025/06/27 07:23:09 - PRUEBA_END_MONTH.hpl - 
2025/06/27 07:23:09 - PRUEBA_END_MONTH.hpl - 
2025/06/27 07:23:09 - PRUEBA_END_MONTH.hpl - 	at org.apache.hop.pipeline.Pipeline.prepareExecution(Pipeline.java:1088)
2025/06/27 07:23:09 - PRUEBA_END_MONTH.hpl - 	at org.apache.hop.pipeline.engines.local.LocalPipelineEngine.prepareExecution(LocalPipelineEngine.java:232)
2025/06/27 07:23:09 - PRUEBA_END_MONTH.hpl - 	at org.apache.hop.pipeline.Pipeline.execute(Pipeline.java:528)
2025/06/27 07:23:09 - PRUEBA_END_MONTH.hpl - 	at org.apache.hop.workflow.actions.pipeline.ActionPipeline.execute(ActionPipeline.java:543)
2025/06/27 07:23:09 - PRUEBA_END_MONTH.hpl - 	at org.apache.hop.workflow.Workflow.executeFromStart(Workflow.java:751)
2025/06/27 07:23:09 - PRUEBA_END_MONTH.hpl - 	at org.apache.hop.workflow.Workf
[2025-06-27T07:23:09.142+0000] {docker.py:436} INFO - low.executeFromStart(Workflow.java:902)
2025/06/27 07:23:09 - PRUEBA_END_MONTH.hpl - 	at org.apache.hop.workflow.Workflow.executeFromStart(Workflow.java:453)
2025/06/27 07:23:09 - PRUEBA_END_MONTH.hpl - 	at org.apache.hop.workflow.Workflow.startExecution(Workflow.java:313)
2025/06/27 07:23:09 - PRUEBA_END_MONTH.hpl - 	at org.apache.hop.workflow.engines.local.LocalWorkflowEngine.startExecution(LocalWorkflowEngine.java:249)
2025/06/27 07:23:09 - PRUEBA_END_MONTH.hpl - 	at org.apache.hop.workflow.actions.workflow.ActionWorkflowRunner.run(ActionWorkflowRunner.java:55)
2025/06/27 07:23:09 - PRUEBA_END_MONTH.hpl - 	at java.base/java.lang.Thread.run(Thread.java:840)
[2025-06-27T07:23:09.285+0000] {docker.py:436} INFO - 2025/06/27 07:23:09 - filename_end_month - Finished action [PRUEBA_END_MONTH.hpl] (result=[false])
2025/06/27 07:23:09 - filename_end_month - Workflow execution finished
[2025-06-27T07:23:09.553+0000] {docker.py:436} INFO - 2025/06/27 07:23:09 - filename_end_month - Workflow duration : 11.924 seconds [ 11.923" ]
[2025-06-27T07:23:09.779+0000] {docker.py:436} INFO - 2025/06/27 07:23:09 - WF_MAIN_END_MONTH - Finished action [filename_end_month.hwf] (result=[false])
2025/06/27 07:23:09 - WF_MAIN_END_MONTH - Workflow execution finished
[2025-06-27T07:23:09.912+0000] {docker.py:436} INFO - 2025/06/27 07:23:09 - WF_MAIN_END_MONTH - Workflow duration : 16.85 seconds [ 16.850" ]
[2025-06-27T07:23:09.917+0000] {docker.py:436} INFO - HopRun exit.
[2025-06-27T07:23:10.963+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-06-27T07:23:11.027+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/docker/api/client.py", line 265, in _raise_for_status
    response.raise_for_status()
  File "/home/airflow/.local/lib/python3.12/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: http+docker://localhost/v1.50/containers/create

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 371, in _run_image
    return self._run_image_with_mounts([*self.mounts, tmp_mount], add_tmp_variable=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 398, in _run_image_with_mounts
    self.container = self.cli.create_container(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/docker/api/container.py", line 439, in create_container
    return self.create_container_from_config(config, name, platform)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/docker/api/container.py", line 456, in create_container_from_config
    return self._result(res, True)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/docker/api/client.py", line 271, in _result
    self._raise_for_status(response)
  File "/home/airflow/.local/lib/python3.12/site-packages/docker/api/client.py", line 267, in _raise_for_status
    raise create_api_error_from_http_exception(e) from e
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/docker/errors.py", line 39, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation) from e
docker.errors.APIError: 400 Client Error for http+docker://localhost/v1.50/containers/create: Bad Request ("invalid mount config for type "bind": bind source path does not exist: /tmp/airflowtmpx0jx4qii")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 509, in execute
    return self._run_image()
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 380, in _run_image
    return self._run_image_with_mounts(self.mounts, add_tmp_variable=False)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 444, in _run_image_with_mounts
    raise DockerContainerFailedException(f"Docker container failed: {result!r}", logs=log_lines)
airflow.providers.docker.exceptions.DockerContainerFailedException: Docker container failed: {'StatusCode': 1}
[2025-06-27T07:23:11.118+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=WF_MAIN_END_MONTH, task_id=run_hop_pipeline, run_id=scheduled__2025-05-01T14:00:00+00:00, execution_date=20250501T140000, start_date=20250627T072046, end_date=20250627T072311
[2025-06-27T07:23:11.251+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 7 for task run_hop_pipeline (Docker container failed: {'StatusCode': 1}; 69)
[2025-06-27T07:23:11.363+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-06-27T07:23:11.453+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-06-27T07:23:11.457+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2025-06-27T07:37:09.177+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-06-27T07:37:09.231+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: WF_MAIN_END_MONTH.run_hop_pipeline scheduled__2025-05-01T14:00:00+00:00 [queued]>
[2025-06-27T07:37:09.248+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: WF_MAIN_END_MONTH.run_hop_pipeline scheduled__2025-05-01T14:00:00+00:00 [queued]>
[2025-06-27T07:37:09.249+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-06-27T07:37:09.276+0000] {taskinstance.py:2330} INFO - Executing <Task(DockerOperator): run_hop_pipeline> on 2025-05-01 14:00:00+00:00
[2025-06-27T07:37:09.291+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=69) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-06-27T07:37:09.295+0000] {standard_task_runner.py:63} INFO - Started process 74 to run task
[2025-06-27T07:37:09.296+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'WF_MAIN_END_MONTH', 'run_hop_pipeline', 'scheduled__2025-05-01T14:00:00+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/apache-hop-dag-wf-main-end-month.py', '--cfg-path', '/tmp/tmp47cm0q4q']
[2025-06-27T07:37:09.300+0000] {standard_task_runner.py:91} INFO - Job 4: Subtask run_hop_pipeline
[2025-06-27T07:37:09.464+0000] {task_command.py:426} INFO - Running <TaskInstance: WF_MAIN_END_MONTH.run_hop_pipeline scheduled__2025-05-01T14:00:00+00:00 [running]> on host ec14a5b8088e
[2025-06-27T07:37:09.642+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='WF_MAIN_END_MONTH' AIRFLOW_CTX_TASK_ID='run_hop_pipeline' AIRFLOW_CTX_EXECUTION_DATE='2025-05-01T14:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-05-01T14:00:00+00:00'
[2025-06-27T07:37:09.644+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-06-27T07:37:09.835+0000] {docker.py:366} INFO - Starting docker container from image apache/hop:latest
[2025-06-27T07:37:09.875+0000] {docker.py:374} WARNING - Using remote engine or docker-in-docker and mounting temporary volume from host is not supported. Falling back to `mount_tmp_dir=False` mode. You can set `mount_tmp_dir` parameter to False to disable mounting and remove the warning
[2025-06-27T07:37:10.854+0000] {docker.py:436} INFO - 2025/06/27 07:37:10 - The project folder for ProyectoSmartMed is set to: /files
[2025-06-27T07:37:10.858+0000] {docker.py:436} INFO - 2025/06/27 07:37:10 - Running the entrypoint script with PID 6
2025/06/27 07:37:10 - The specified project folder exists
[2025-06-27T07:37:10.861+0000] {docker.py:436} INFO - 2025/06/27 07:37:10 - Registering project ProyectoSmartMed in the Hop container configuration
[2025-06-27T07:37:10.862+0000] {docker.py:436} INFO - 2025/06/27 07:37:10 - /opt/hop/hop-conf.sh --project=ProyectoSmartMed --project-create --project-home='/files' --project-config-file='project-config.json'
[2025-06-27T07:38:02.337+0000] {docker.py:436} INFO - Creating project 'ProyectoSmartMed'
[2025-06-27T07:38:02.850+0000] {docker.py:436} INFO - Project 'ProyectoSmartMed' was created for home folder : /files
[2025-06-27T07:38:02.993+0000] {docker.py:436} INFO - Configuration file for project 'ProyectoSmartMed' was saved to : file:/files/project-config.json
[2025-06-27T07:38:03.148+0000] {docker.py:436} INFO - 2025/06/27 07:38:03 - Not creating an environment in the container
[2025-06-27T07:38:03.153+0000] {docker.py:436} INFO - 2025/06/27 07:38:03 - Running a single hop workflow / pipeline (${PROJECT_HOME}/workflows/WF_MAIN_END_MONTH.hwf)
[2025-06-27T07:38:30.268+0000] {docker.py:436} INFO - 2025/06/27 07:38:30 - HopRun - Enabling project 'ProyectoSmartMed'
[2025-06-27T07:38:30.768+0000] {docker.py:436} INFO - 2025/06/27 07:38:30 - HopRun - Starting workflow: /files/workflows/WF_MAIN_END_MONTH.hwf
[2025-06-27T07:38:33.923+0000] {docker.py:436} INFO - 2025/06/27 07:38:33 - WF_MAIN_END_MONTH - Start of workflow execution
[2025-06-27T07:38:34.207+0000] {docker.py:436} INFO - 2025/06/27 07:38:34 - WF_MAIN_END_MONTH - Starting action [filename_end_month.hwf]
[2025-06-27T07:38:34.821+0000] {docker.py:436} INFO - 2025/06/27 07:38:34 - filename_end_month - Start of workflow execution
[2025-06-27T07:38:34.846+0000] {docker.py:436} INFO - 2025/06/27 07:38:34 - filename_end_month - Starting action [PRUEBA_END_MONTH.hpl]
[2025-06-27T07:38:34.946+0000] {docker.py:436} INFO - 2025/06/27 07:38:34 - PRUEBA_END_MONTH.hpl - Using run configuration [local]
[2025-06-27T07:38:35.013+0000] {docker.py:436} INFO - 2025/06/27 07:38:35 - PRUEBA_END_MONTH - Executing this pipeline using the Local Pipeline Engine with run configuration 'local'
[2025-06-27T07:38:35.023+0000] {docker.py:436} INFO - 2025/06/27 07:38:35 - PRUEBA_END_MONTH - Execution started for pipeline [PRUEBA_END_MONTH]
[2025-06-27T07:38:39.280+0000] {docker.py:436} INFO - 2025/06/27 07:38:39 - Table input.0 - Finished reading query, closing connection.
2025/06/27 07:38:39 - Set variables.0 - Setting project variables...
2025/06/27 07:38:39 - Set variables.0 - Set variable lastDate to value [2025-05-01]
[2025-06-27T07:38:39.285+0000] {docker.py:436} INFO - 2025/06/27 07:38:39 - Set variables 2.0 - Setting project variables...
2025/06/27 07:38:39 - Set variables 2.0 - Set variable endDate to value [2025-05-31]
[2025-06-27T07:38:39.310+0000] {docker.py:436} INFO - 2025/06/27 07:38:39 - Set variables.0 - Finished after 1 rows.
[2025-06-27T07:38:39.312+0000] {docker.py:436} INFO - 2025/06/27 07:38:39 - Set variables.0 - Finished processing (I=0, O=0, R=1, W=1, U=0, E=0)
[2025-06-27T07:38:39.319+0000] {docker.py:436} INFO - 2025/06/27 07:38:39 - Dummy (do nothing).0 - Finished processing (I=0, O=0, R=1, W=1, U=0, E=0)
[2025-06-27T07:38:39.325+0000] {docker.py:436} INFO - 2025/06/27 07:38:39 - Dummy (do nothing) 2.0 - Finished processing (I=0, O=0, R=1, W=1, U=0, E=0)
[2025-06-27T07:38:39.348+0000] {docker.py:436} INFO - 2025/06/27 07:38:39 - Set variables 2.0 - Finished after 1 rows.
2025/06/27 07:38:39 - Set variables 2.0 - Finished processing (I=0, O=0, R=1, W=1, U=0, E=0)
[2025-06-27T07:38:39.445+0000] {docker.py:436} INFO - 2025/06/27 07:38:39 - Table input.0 - Finished processing (I=1, O=0, R=0, W=1, U=0, E=0)
[2025-06-27T07:38:39.521+0000] {docker.py:436} INFO - 2025/06/27 07:38:39 - PRUEBA_END_MONTH - Pipeline duration : 4.44 seconds [  4.440" ]
[2025-06-27T07:38:39.731+0000] {docker.py:436} INFO - 2025/06/27 07:38:39 - PRUEBA_END_MONTH - Execution finished on a local pipeline engine with run configuration 'local'
[2025-06-27T07:38:39.750+0000] {docker.py:436} INFO - 2025/06/27 07:38:39 - filename_end_month - Starting action [End Repeat]
[2025-06-27T07:38:39.782+0000] {docker.py:436} INFO - 2025/06/27 07:38:39 - filename_end_month - Finished action [End Repeat] (result=[true])
[2025-06-27T07:38:39.783+0000] {docker.py:436} INFO - 2025/06/27 07:38:39 - filename_end_month - Finished action [PRUEBA_END_MONTH.hpl] (result=[true])
2025/06/27 07:38:39 - filename_end_month - Workflow execution finished
[2025-06-27T07:38:39.811+0000] {docker.py:436} INFO - 2025/06/27 07:38:39 - filename_end_month - Workflow duration : 5.484 seconds [  5.484" ]
[2025-06-27T07:38:39.819+0000] {docker.py:436} INFO - 2025/06/27 07:38:39 - WF_MAIN_END_MONTH - Starting action [WF_CARGA_FUENTES.hwf]
[2025-06-27T07:38:40.727+0000] {docker.py:436} INFO - 2025/06/27 07:38:40 - WF_CARGA_FUENTES - Start of workflow execution
[2025-06-27T07:38:40.761+0000] {docker.py:436} INFO - 2025/06/27 07:38:40 - WF_CARGA_FUENTES - Starting action [CARGA_MODELOS.hpl]
[2025-06-27T07:38:40.844+0000] {docker.py:436} INFO - 2025/06/27 07:38:40 - CARGA_MODELOS.hpl - Using run configuration [local]
[2025-06-27T07:38:40.921+0000] {docker.py:436} INFO - 2025/06/27 07:38:40 - CARGA_MODELOS - Executing this pipeline using the Local Pipeline Engine with run configuration 'local'
[2025-06-27T07:38:40.928+0000] {docker.py:436} INFO - 2025/06/27 07:38:40 - CARGA_MODELOS - Execution started for pipeline [CARGA_MODELOS]
[2025-06-27T07:38:45.713+0000] {docker.py:436} INFO - 2025/06/27 07:38:45 - as_meter_model.0 - Finished reading query, closing connection.
[2025-06-27T07:38:45.715+0000] {docker.py:436} INFO - 2025/06/27 07:38:45 - as_meter_model.0 - Finished processing (I=111, O=0, R=0, W=111, U=0, E=0)
[2025-06-27T07:38:45.764+0000] {docker.py:436} INFO - 2025/06/27 07:38:45 - modelos_csv.0 - Finished processing (I=0, O=112, R=111, W=111, U=0, E=0)
[2025-06-27T07:38:45.765+0000] {docker.py:436} INFO - 2025/06/27 07:38:45 - CARGA_MODELOS - Pipeline duration : 4.845 seconds [  4.844" ]
[2025-06-27T07:38:45.791+0000] {docker.py:436} INFO - 2025/06/27 07:38:45 - CARGA_MODELOS - Execution finished on a local pipeline engine with run configuration 'local'
[2025-06-27T07:38:45.795+0000] {docker.py:436} INFO - 2025/06/27 07:38:45 - WF_CARGA_FUENTES - Starting action [End Repeat]
[2025-06-27T07:38:45.812+0000] {docker.py:436} INFO - 2025/06/27 07:38:45 - WF_CARGA_FUENTES - Finished action [End Repeat] (result=[true])
[2025-06-27T07:38:45.813+0000] {docker.py:436} INFO - 2025/06/27 07:38:45 - WF_CARGA_FUENTES - Finished action [CARGA_MODELOS.hpl] (result=[true])
2025/06/27 07:38:45 - WF_CARGA_FUENTES - Starting action [CARGA_MEDIDORES.hpl]
[2025-06-27T07:38:45.847+0000] {docker.py:436} INFO - 2025/06/27 07:38:45 - CARGA_MEDIDORES.hpl - Using run configuration [local]
[2025-06-27T07:38:45.876+0000] {docker.py:436} INFO - 2025/06/27 07:38:45 - CARGA_MEDIDORES - Executing this pipeline using the Local Pipeline Engine with run configuration 'local'
[2025-06-27T07:38:45.879+0000] {docker.py:436} INFO - 2025/06/27 07:38:45 - CARGA_MEDIDORES - Execution started for pipeline [CARGA_MEDIDORES]
[2025-06-27T07:38:51.274+0000] {docker.py:436} INFO - 2025/06/27 07:38:51 - as_meter.0 - Finished reading query, closing connection.
[2025-06-27T07:38:51.275+0000] {docker.py:436} INFO - 2025/06/27 07:38:51 - as_meter.0 - Finished processing (I=32434, O=0, R=0, W=32434, U=0, E=0)
[2025-06-27T07:38:51.759+0000] {docker.py:436} INFO - 2025/06/27 07:38:51 - medidores.0 - Finished processing (I=0, O=32435, R=32434, W=32434, U=0, E=0)
2025/06/27 07:38:51 - CARGA_MEDIDORES - Pipeline duration : 5.881 seconds [  5.881" ]
[2025-06-27T07:38:51.806+0000] {docker.py:436} INFO - 2025/06/27 07:38:51 - CARGA_MEDIDORES - Execution finished on a local pipeline engine with run configuration 'local'
[2025-06-27T07:38:51.815+0000] {docker.py:436} INFO - 2025/06/27 07:38:51 - WF_CARGA_FUENTES - Starting action [End Repeat]
[2025-06-27T07:38:51.840+0000] {docker.py:436} INFO - 2025/06/27 07:38:51 - WF_CARGA_FUENTES - Finished action [End Repeat] (result=[true])
2025/06/27 07:38:51 - WF_CARGA_FUENTES - Finished action [CARGA_MEDIDORES.hpl] (result=[true])
2025/06/27 07:38:51 - WF_CARGA_FUENTES - Starting action [CARGA_HECHOS.hpl]
[2025-06-27T07:38:51.880+0000] {docker.py:436} INFO - 2025/06/27 07:38:51 - CARGA_HECHOS.hpl - Using run configuration [local]
[2025-06-27T07:38:51.923+0000] {docker.py:436} INFO - 2025/06/27 07:38:51 - CARGA_HECHOS - Executing this pipeline using the Local Pipeline Engine with run configuration 'local'
[2025-06-27T07:38:51.924+0000] {docker.py:436} INFO - 2025/06/27 07:38:51 - CARGA_HECHOS - Execution started for pipeline [CARGA_HECHOS]
[2025-06-27T07:42:59.923+0000] {docker.py:436} INFO - 2025/06/27 07:42:59 - t_realtimedata.0 - Finished reading query, closing connection.
[2025-06-27T07:42:59.924+0000] {docker.py:436} INFO - 2025/06/27 07:42:59 - t_realtimedata.0 - Finished processing (I=3492965, O=0, R=0, W=3492965, U=0, E=0)
[2025-06-27T07:43:00.097+0000] {docker.py:436} INFO - 2025/06/27 07:43:00 - hechos_hurtos_Csv.0 - Finished processing (I=0, O=3492966, R=3492965, W=3492965, U=0, E=0)
[2025-06-27T07:43:00.098+0000] {docker.py:436} INFO - 2025/06/27 07:43:00 - CARGA_HECHOS - Pipeline duration : 248.179 seconds [  4'  8" ]
[2025-06-27T07:43:00.116+0000] {docker.py:436} INFO - 2025/06/27 07:43:00 - CARGA_HECHOS - Execution finished on a local pipeline engine with run configuration 'local'
[2025-06-27T07:43:00.118+0000] {docker.py:436} INFO - 2025/06/27 07:43:00 - WF_CARGA_FUENTES - Starting action [End Repeat]
[2025-06-27T07:43:00.124+0000] {docker.py:436} INFO - 2025/06/27 07:43:00 - WF_CARGA_FUENTES - Finished action [End Repeat] (result=[true])
2025/06/27 07:43:00 - WF_CARGA_FUENTES - Finished action [CARGA_HECHOS.hpl] (result=[true])
2025/06/27 07:43:00 - WF_CARGA_FUENTES - Starting action [CARGA_DIAGNOSE.hpl]
[2025-06-27T07:43:00.150+0000] {docker.py:436} INFO - 2025/06/27 07:43:00 - CARGA_DIAGNOSE.hpl - Using run configuration [local]
[2025-06-27T07:43:00.164+0000] {docker.py:436} INFO - 2025/06/27 07:43:00 - CARGA_DIAGNOSE - Executing this pipeline using the Local Pipeline Engine with run configuration 'local'
[2025-06-27T07:43:00.167+0000] {docker.py:436} INFO - 2025/06/27 07:43:00 - CARGA_DIAGNOSE - Execution started for pipeline [CARGA_DIAGNOSE]
[2025-06-27T07:43:06.288+0000] {docker.py:436} INFO - 2025/06/27 07:43:06 - as_water_alarm_diagnose.0 - Finished reading query, closing connection.
[2025-06-27T07:43:06.288+0000] {docker.py:436} INFO - 2025/06/27 07:43:06 - as_water_alarm_diagnose.0 - Finished processing (I=16469, O=0, R=0, W=16469, U=0, E=0)
[2025-06-27T07:43:06.433+0000] {docker.py:436} INFO - 2025/06/27 07:43:06 - diagnose_csv.0 - Finished processing (I=0, O=16470, R=16469, W=16469, U=0, E=0)
[2025-06-27T07:43:06.434+0000] {docker.py:436} INFO - 2025/06/27 07:43:06 - CARGA_DIAGNOSE - Pipeline duration : 6.268 seconds [  6.267" ]
[2025-06-27T07:43:06.448+0000] {docker.py:436} INFO - 2025/06/27 07:43:06 - CARGA_DIAGNOSE - Execution finished on a local pipeline engine with run configuration 'local'
[2025-06-27T07:43:06.451+0000] {docker.py:436} INFO - 2025/06/27 07:43:06 - WF_CARGA_FUENTES - Starting action [End Repeat]
[2025-06-27T07:43:06.455+0000] {docker.py:436} INFO - 2025/06/27 07:43:06 - WF_CARGA_FUENTES - Finished action [End Repeat] (result=[true])
2025/06/27 07:43:06 - WF_CARGA_FUENTES - Finished action [CARGA_DIAGNOSE.hpl] (result=[true])
2025/06/27 07:43:06 - WF_CARGA_FUENTES - Starting action [CARGA_DEPARTAMENTOS.hpl]
[2025-06-27T07:43:06.474+0000] {docker.py:436} INFO - 2025/06/27 07:43:06 - CARGA_DEPARTAMENTOS.hpl - Using run configuration [local]
[2025-06-27T07:43:06.488+0000] {docker.py:436} INFO - 2025/06/27 07:43:06 - CARGA_DEPARTAMENTOS - Executing this pipeline using the Local Pipeline Engine with run configuration 'local'
[2025-06-27T07:43:06.491+0000] {docker.py:436} INFO - 2025/06/27 07:43:06 - CARGA_DEPARTAMENTOS - Execution started for pipeline [CARGA_DEPARTAMENTOS]
[2025-06-27T07:43:09.076+0000] {docker.py:436} INFO - 2025/06/27 07:43:09 - ss_dept.0 - Finished reading query, closing connection.
[2025-06-27T07:43:09.078+0000] {docker.py:436} INFO - 2025/06/27 07:43:09 - ss_dept.0 - Finished processing (I=117, O=0, R=0, W=117, U=0, E=0)
[2025-06-27T07:43:09.109+0000] {docker.py:436} INFO - 2025/06/27 07:43:09 - regiones_csv.0 - Finished processing (I=0, O=118, R=117, W=117, U=0, E=0)
[2025-06-27T07:43:09.110+0000] {docker.py:436} INFO - 2025/06/27 07:43:09 - CARGA_DEPARTAMENTOS - Pipeline duration : 2.622 seconds [  2.621" ]
[2025-06-27T07:43:09.117+0000] {docker.py:436} INFO - 2025/06/27 07:43:09 - CARGA_DEPARTAMENTOS - Execution finished on a local pipeline engine with run configuration 'local'
[2025-06-27T07:43:09.120+0000] {docker.py:436} INFO - 2025/06/27 07:43:09 - WF_CARGA_FUENTES - Starting action [End Repeat]
[2025-06-27T07:43:09.125+0000] {docker.py:436} INFO - 2025/06/27 07:43:09 - WF_CARGA_FUENTES - Finished action [End Repeat] (result=[true])
2025/06/27 07:43:09 - WF_CARGA_FUENTES - Finished action [CARGA_DEPARTAMENTOS.hpl] (result=[true])
[2025-06-27T07:43:09.130+0000] {docker.py:436} INFO - 2025/06/27 07:43:09 - WF_CARGA_FUENTES - Starting action [CARGA_ALARMAS.hpl]
[2025-06-27T07:43:09.142+0000] {docker.py:436} INFO - 2025/06/27 07:43:09 - CARGA_ALARMAS.hpl - Using run configuration [local]
[2025-06-27T07:43:09.153+0000] {docker.py:436} INFO - 2025/06/27 07:43:09 - CARGA_ALARMAS - Executing this pipeline using the Local Pipeline Engine with run configuration 'local'
[2025-06-27T07:43:09.156+0000] {docker.py:436} INFO - 2025/06/27 07:43:09 - CARGA_ALARMAS - Execution started for pipeline [CARGA_ALARMAS]
[2025-06-27T07:43:51.739+0000] {docker.py:436} INFO - 2025/06/27 07:43:51 - as_water_alarm.0 - Finished reading query, closing connection.
[2025-06-27T07:43:51.740+0000] {docker.py:436} INFO - 2025/06/27 07:43:51 - as_water_alarm.0 - Finished processing (I=1082733, O=0, R=0, W=1082733, U=0, E=0)
[2025-06-27T07:43:51.815+0000] {docker.py:436} INFO - 2025/06/27 07:43:51 - alarmas_CSV.0 - Finished processing (I=0, O=1082734, R=1082733, W=1082733, U=0, E=0)
[2025-06-27T07:43:51.815+0000] {docker.py:436} INFO - 2025/06/27 07:43:51 - CARGA_ALARMAS - Pipeline duration : 42.661 seconds [ 42.661" ]
[2025-06-27T07:43:51.826+0000] {docker.py:436} INFO - 2025/06/27 07:43:51 - CARGA_ALARMAS - Execution finished on a local pipeline engine with run configuration 'local'
[2025-06-27T07:43:51.829+0000] {docker.py:436} INFO - 2025/06/27 07:43:51 - WF_CARGA_FUENTES - Starting action [End Repeat]
[2025-06-27T07:43:51.834+0000] {docker.py:436} INFO - 2025/06/27 07:43:51 - WF_CARGA_FUENTES - Finished action [End Repeat] (result=[true])
2025/06/27 07:43:51 - WF_CARGA_FUENTES - Finished action [CARGA_ALARMAS.hpl] (result=[true])
[2025-06-27T07:43:51.835+0000] {docker.py:436} INFO - 2025/06/27 07:43:51 - WF_CARGA_FUENTES - Workflow execution finished
[2025-06-27T07:43:51.837+0000] {docker.py:436} INFO - 2025/06/27 07:43:51 - WF_CARGA_FUENTES - Workflow duration : 311.877 seconds [  5' 11" ]
[2025-06-27T07:43:51.840+0000] {docker.py:436} INFO - 2025/06/27 07:43:51 - WF_MAIN_END_MONTH - Starting action [WF_MEDIDORES.hwf]
[2025-06-27T07:43:52.149+0000] {docker.py:436} INFO - 2025/06/27 07:43:52 - WF_MEDIDORES - Start of workflow execution
[2025-06-27T07:43:52.156+0000] {docker.py:436} INFO - 2025/06/27 07:43:52 - WF_MEDIDORES - Starting action [STG1_MEDIDORES.hpl]
[2025-06-27T07:43:52.191+0000] {docker.py:436} INFO - 2025/06/27 07:43:52 - STG1_MEDIDORES.hpl - Using run configuration [local]
[2025-06-27T07:43:52.203+0000] {docker.py:436} INFO - 2025/06/27 07:43:52 - STG1_MEDIDORES - Executing this pipeline using the Local Pipeline Engine with run configuration 'local'
[2025-06-27T07:43:52.206+0000] {docker.py:436} INFO - 2025/06/27 07:43:52 - STG1_MEDIDORES - Execution started for pipeline [STG1_MEDIDORES]
[2025-06-27T07:43:52.980+0000] {docker.py:436} INFO - 2025/06/27 07:43:52 - Table output.0 - Connected to database [POSTGRES_SMART] (commit=3000)
[2025-06-27T07:43:53.300+0000] {docker.py:436} INFO - 2025/06/27 07:43:53 - METER_CSV.0 - Header row skipped in file '/files/FuentesSmartMed/medidores.csv'
[2025-06-27T07:44:03.460+0000] {docker.py:436} INFO - 2025/06/27 07:44:03 - METER_CSV.0 - Finished processing (I=32435, O=0, R=0, W=32434, U=0, E=0)
[2025-06-27T07:44:08.624+0000] {docker.py:436} INFO - 2025/06/27 07:44:08 - Table output.0 - Finished processing (I=0, O=32434, R=32434, W=32434, U=0, E=0)
2025/06/27 07:44:08 - STG1_MEDIDORES - Pipeline duration : 16.419 seconds [ 16.419" ]
[2025-06-27T07:44:08.654+0000] {docker.py:436} INFO - 2025/06/27 07:44:08 - STG1_MEDIDORES - Execution finished on a local pipeline engine with run configuration 'local'
[2025-06-27T07:44:08.657+0000] {docker.py:436} INFO - 2025/06/27 07:44:08 - WF_MEDIDORES - Starting action [STG2_MEDIDORES.hpl]
[2025-06-27T07:44:08.691+0000] {docker.py:436} INFO - 2025/06/27 07:44:08 - STG2_MEDIDORES.hpl - Using run configuration [local]
[2025-06-27T07:44:08.714+0000] {docker.py:436} INFO - 2025/06/27 07:44:08 - STG2_MEDIDORES - Executing this pipeline using the Local Pipeline Engine with run configuration 'local'
[2025-06-27T07:44:08.725+0000] {docker.py:436} INFO - 2025/06/27 07:44:08 - STG2_MEDIDORES - Execution started for pipeline [STG2_MEDIDORES]
[2025-06-27T07:44:09.570+0000] {docker.py:436} INFO - 2025/06/27 07:44:09 - STG2_MEDIDORES.0 - Connected to database [POSTGRES_SMART] (commit=1000)
[2025-06-27T07:44:23.669+0000] {docker.py:436} INFO - 2025/06/27 07:44:23 - STG1_MEDIDORES.0 - Finished reading query, closing connection.
[2025-06-27T07:44:23.778+0000] {docker.py:436} INFO - 2025/06/27 07:44:23 - STG1_MEDIDORES.0 - Finished processing (I=32434, O=0, R=0, W=32434, U=0, E=0)
[2025-06-27T07:44:28.968+0000] {docker.py:436} INFO - 2025/06/27 07:44:28 - STG2_MEDIDORES.0 - Finished processing (I=0, O=32434, R=32434, W=32434, U=0, E=0)
[2025-06-27T07:44:28.973+0000] {docker.py:436} INFO - 2025/06/27 07:44:28 - STG2_MEDIDORES - Pipeline duration : 20.254 seconds [ 20.254" ]
[2025-06-27T07:44:28.981+0000] {docker.py:436} INFO - 2025/06/27 07:44:28 - STG2_MEDIDORES - Execution finished on a local pipeline engine with run configuration 'local'
[2025-06-27T07:44:28.983+0000] {docker.py:436} INFO - 2025/06/27 07:44:28 - WF_MEDIDORES - Starting action [STG3_MEDIDORES.hpl]
[2025-06-27T07:44:29.007+0000] {docker.py:436} INFO - 2025/06/27 07:44:29 - STG3_MEDIDORES.hpl - Using run configuration [local]
[2025-06-27T07:44:29.017+0000] {docker.py:436} INFO - 2025/06/27 07:44:29 - STG3_MEDIDORES - Executing this pipeline using the Local Pipeline Engine with run configuration 'local'
[2025-06-27T07:44:29.019+0000] {docker.py:436} INFO - 2025/06/27 07:44:29 - STG3_MEDIDORES - Execution started for pipeline [STG3_MEDIDORES]
[2025-06-27T07:44:29.839+0000] {docker.py:436} INFO - 2025/06/27 07:44:29 - STG3_MEDIDORES.0 - Connected to database [POSTGRES_SMART] (commit=1000)
[2025-06-27T07:44:33.187+0000] {docker.py:436} INFO - 2025/06/27 07:44:33 - STG3_MEDIDORES - Warning: unable to register execution info (data and state) at location local-audit(non-fatal)
[2025-06-27T07:44:33.535+0000] {docker.py:436} INFO - 2025/06/27 07:44:33 - STG2_MEDIDORES.0 - Finished reading query, closing connection.
[2025-06-27T07:44:33.635+0000] {docker.py:436} INFO - 2025/06/27 07:44:33 - STG2_MEDIDORES.0 - Finished processing (I=32434, O=0, R=0, W=32434, U=0, E=0)
[2025-06-27T07:44:38.177+0000] {docker.py:436} INFO - 2025/06/27 07:44:38 - STG3_MEDIDORES - Warning: unable to register execution info (data and state) at location local-audit(non-fatal)
[2025-06-27T07:44:38.822+0000] {docker.py:436} INFO - 2025/06/27 07:44:38 - Strings cut.0 - Finished processing (I=0, O=0, R=32434, W=32434, U=0, E=0)
[2025-06-27T07:44:43.181+0000] {docker.py:436} INFO - 2025/06/27 07:44:43 - STG3_MEDIDORES - Warning: unable to register execution info (data and state) at location local-audit(non-fatal)
[2025-06-27T07:44:44.178+0000] {docker.py:436} INFO - 2025/06/27 07:44:44 - Select values.0 - Finished processing (I=0, O=0, R=32434, W=32434, U=0, E=0)
[2025-06-27T07:44:48.176+0000] {docker.py:436} INFO - 2025/06/27 07:44:48 - STG3_MEDIDORES - Warning: unable to register execution info (data and state) at location local-audit(non-fatal)
[2025-06-27T07:44:49.803+0000] {docker.py:436} INFO - 2025/06/27 07:44:49 - STG3_MEDIDORES.0 - Finished processing (I=0, O=32434, R=32434, W=32434, U=0, E=0)
[2025-06-27T07:44:49.804+0000] {docker.py:436} INFO - 2025/06/27 07:44:49 - STG3_MEDIDORES - Pipeline duration : 20.787 seconds [ 20.786" ]
[2025-06-27T07:44:49.811+0000] {docker.py:436} INFO - 2025/06/27 07:44:49 - STG3_MEDIDORES - ERROR: Error handling writing final pipeline state to location (non-fatal)
[2025-06-27T07:44:49.812+0000] {docker.py:436} INFO - 2025/06/27 07:44:49 - STG3_MEDIDORES - ERROR: org.apache.hop.core.exception.HopException: 
2025/06/27 07:44:49 - STG3_MEDIDORES - Error storing execution data
2025/06/27 07:44:49 - STG3_MEDIDORES - new_creator_date String(2147483647) : There was a data type error: the data type of java.sql.Timestamp object [2020-07-01 21:25:23.0] does not correspond to value meta [String(2147483647)] (through reference chain: org.apache.hop.execution.ExecutionData["rowsBinaryGzipBase64Encoded"])
2025/06/27 07:44:49 - STG3_MEDIDORES - 
2025/06/27 07:44:49 - STG3_MEDIDORES - 	at org.apache.hop.execution.local.FileExecutionInfoLocation.registerData(FileExecutionInfoLocation.java:348)
2025/06/27 07:44:49 - STG3_MEDIDORES - 	at org.apache.hop.pipeline.engines.local.LocalPipelineEngine.stopTransformExecutionInfoTimer(LocalPipelineEngine.java:503)
2025/06/27 07:44:49 - STG3_MEDIDORES - 	at org.apache.hop.pipeline.engines.local.LocalPipelineEngine.pipelineCompleted(LocalPipelineEngine.java:460)
2025/06/27 07:44:49 - STG3_MEDIDORES - 	at org.apache.hop.pipeline.Pipeline.fireExecutionFinishedListeners(Pipeline.java:1344)
2025/06/27 07:44:49 - STG3_MEDIDORES - 	at org.apache.hop.pipeline.Pipeline.lambda$startThreads$0(Pipeline.java:1141)
2025/06/27 07:44:49 - STG3_MEDIDORES - 	at org.apache.hop.pipeline.transform.BaseTransform.fireTransformFinishedListeners(BaseTransform.java:2840)
2025/06/27 07:44:49 - STG3_MEDIDORES - 	at org.apache.hop.pipeline.transform.BaseTransform.markStop(BaseTransform.java:2833)
2025/06/27 07:44:49 - STG3_MEDIDORES - 	at org.apache.hop.pipeline.transform.RunThread.run(RunThread.java:141)
2025/06/27 07:44:49 - STG3_MEDIDORES - 	at java.base/java.lang.Thread.run(Thread.java:840)
2025/06/27 07:44:49 - STG3_MEDIDORES - Caused by: com.fasterxml.jackson.databind.JsonMappingException: new_creator_date String(2147483647) : There was a data type error: the data type of java.sql.Timestamp object [2020-07-01 21:25:23.0] does not correspond to value meta [String(2147483647)] (through reference chain: org.apache.hop.execution.ExecutionData["rowsBinaryGzipBase64Encoded"])
2025/06/27 07:44:49 - STG3_MEDIDORES - 	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:402)
2025/06/27 07:44:49 - STG3_MEDIDORES - 	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:361)
2025/06/27 07:44:49 - STG3_MEDIDORES - 	at com.fasterxml.jackson.databind.ser.std.StdSerializer.wrapAndThrow(StdSerializer.java:323)
2025/06/27 07:44:49 - STG3_MEDIDORES - 	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:780)
2025/06/27 07:44:49 - STG3_MEDIDORES - 	at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:178)
2025/06/27 07:44:49 - STG3_MEDIDORES - 	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider._serialize(DefaultSerializerProvider.java:479)
2025/06/27 07:44:49 - STG3_MEDIDORES - 	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:318)
2025/06/27 07:44:49 - STG3_MEDIDORES - 	at com.fasterxml.jackson.databind.ObjectWriter$Prefetch.serialize(ObjectWriter.java:1572)
2025/06/27 07:44:49 - STG3_MEDIDORES - 	at com.fasterxml.jackson.databind.ObjectWriter._writeValueAndClose(ObjectWriter.java:1273)
2025/06/27 07:44:49 - STG3_MEDIDORES - 	at com.fasterxml.jackson.databind.ObjectWriter.writeValue(ObjectWriter.java:1098)
2025/06/27 07:44:49 - STG3_MEDIDORES - 	at org.apache.hop.execution.local.FileExecutionInfoLocation.registerData(FileExecutionInfoLocation.java:345)
2025/06/27 07:44:49 - STG3_MEDIDORES - 	... 8 more
2025/06/27 07:44:49 - STG3_MEDIDORES - Caused by: java.lang.RuntimeException: new_creator_date String(2147483647) : There was a data type error: the data type of java.sql.Timestamp object [2020-07-01 21:25:23.0] does not correspond to value meta [String(2147483647)]
2025/06/27 07:44:49 - STG3_MEDIDORES - 	at org.apache.hop.core.row.value.ValueMetaBase.writeData(ValueMetaBase.java:3457)
2025/06/27 07:44:49 - STG3_MEDIDORES - 	at org.apache.hop.core.row.RowMeta.writeData(RowMeta.java:719)
2025/06/27 07:44:49 - STG3_MEDIDORES - 	at org.apache.hop.execution.ExecutionData.getRowsBinaryGzipBase64Encoded(ExecutionData.java:193)
2025/06/27 07:44:49 - STG3_MEDIDORES - 	at jdk.internal.reflect.GeneratedMethodAccessor99.invoke(Unknown Source)
2025/06/27 07:44:49 - STG3_MEDIDORES - 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2025/06/27 07:44:49 - STG3_MEDIDORES - 	at java.base/java.lang.reflect.Method.invoke(Method.java:569)
2025/06/27 07:44:49 - STG3_MEDIDORES - 	at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:688)
2025/06/27 07:44:49 - STG3_MEDIDORES - 	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:772)
2025/06/27 07:44:49 - STG3_MEDIDORES - 	... 15 more
2025/06/27 07:44:49 - STG3_MEDIDORES - Execution finished on a local pipeline engine with run configuration 'local'
[2025-06-27T07:44:49.814+0000] {docker.py:436} INFO - 2025/06/27 07:44:49 - WF_MEDIDORES - Starting action [STG4_MEDIDORES.hpl]
[2025-06-27T07:44:49.830+0000] {docker.py:436} INFO - 2025/06/27 07:44:49 - STG4_MEDIDORES.hpl - Using run configuration [local]
[2025-06-27T07:44:49.840+0000] {docker.py:436} INFO - 2025/06/27 07:44:49 - STG4_MEDIDORES - Executing this pipeline using the Local Pipeline Engine with run configuration 'local'
[2025-06-27T07:44:49.843+0000] {docker.py:436} INFO - 2025/06/27 07:44:49 - STG4_MEDIDORES - Execution started for pipeline [STG4_MEDIDORES]
[2025-06-27T07:44:50.571+0000] {docker.py:436} INFO - 2025/06/27 07:44:50 - STG4_MEDIDORES.0 - Connected to database [POSTGRES_SMART] (commit=1000)
[2025-06-27T07:44:56.164+0000] {docker.py:436} INFO - 2025/06/27 07:44:56 - STG3_MEDIDORES.0 - Finished reading query, closing connection.
[2025-06-27T07:44:56.268+0000] {docker.py:436} INFO - 2025/06/27 07:44:56 - STG3_MEDIDORES.0 - Finished processing (I=16398, O=0, R=0, W=16398, U=0, E=0)
[2025-06-27T07:45:01.507+0000] {docker.py:436} INFO - 2025/06/27 07:45:01 - STG4_MEDIDORES.0 - Finished processing (I=0, O=16398, R=16398, W=16398, U=0, E=0)
[2025-06-27T07:45:01.508+0000] {docker.py:436} INFO - 2025/06/27 07:45:01 - STG4_MEDIDORES - Pipeline duration : 11.666 seconds [ 11.666" ]
[2025-06-27T07:45:01.519+0000] {docker.py:436} INFO - 2025/06/27 07:45:01 - STG4_MEDIDORES - Execution finished on a local pipeline engine with run configuration 'local'
[2025-06-27T07:45:01.522+0000] {docker.py:436} INFO - 2025/06/27 07:45:01 - WF_MEDIDORES - Starting action [WF_METERDATA.hwf]
[2025-06-27T07:45:01.896+0000] {docker.py:436} INFO - 2025/06/27 07:45:01 - WF_METERDATA - Start of workflow execution
[2025-06-27T07:45:01.902+0000] {docker.py:436} INFO - 2025/06/27 07:45:01 - WF_METERDATA - Starting action [STG1_METERDATA.hpl]
[2025-06-27T07:45:01.918+0000] {docker.py:436} INFO - 2025/06/27 07:45:01 - STG1_METERDATA.hpl - Using run configuration [local]
[2025-06-27T07:45:01.928+0000] {docker.py:436} INFO - 2025/06/27 07:45:01 - STG1_METERDATA - Executing this pipeline using the Local Pipeline Engine with run configuration 'local'
[2025-06-27T07:45:01.930+0000] {docker.py:436} INFO - 2025/06/27 07:45:01 - STG1_METERDATA - Execution started for pipeline [STG1_METERDATA]
[2025-06-27T07:45:02.689+0000] {docker.py:436} INFO - 2025/06/27 07:45:02 - STG1_METER_DATA.0 - Connected to database [POSTGRES_SMART] (commit=1000)
[2025-06-27T07:45:03.140+0000] {docker.py:436} INFO - 2025/06/27 07:45:03 - METER_DATA.CSV.0 - Header row skipped in file '/files/FuentesSmartMed/meter_data.csv'
[2025-06-27T07:45:03.143+0000] {docker.py:436} INFO - 2025/06/27 07:45:03 - METER_DATA.CSV.0 - Finished processing (I=19, O=0, R=0, W=18, U=0, E=0)
[2025-06-27T07:45:03.458+0000] {docker.py:436} INFO - 2025/06/27 07:45:03 - STG1_METER_DATA.0 - Finished processing (I=0, O=18, R=18, W=18, U=0, E=0)
[2025-06-27T07:45:03.462+0000] {docker.py:436} INFO - 2025/06/27 07:45:03 - STG1_METERDATA - Pipeline duration : 1.53 seconds [  1.530" ]
[2025-06-27T07:45:03.465+0000] {docker.py:436} INFO - 2025/06/27 07:45:03 - STG1_METERDATA - Execution finished on a local pipeline engine with run configuration 'local'
[2025-06-27T07:45:03.468+0000] {docker.py:436} INFO - 2025/06/27 07:45:03 - WF_METERDATA - Starting action [STG2_METERDATA.hpl]
[2025-06-27T07:45:03.492+0000] {docker.py:436} INFO - 2025/06/27 07:45:03 - STG2_METERDATA.hpl - Using run configuration [local]
[2025-06-27T07:45:03.504+0000] {docker.py:436} INFO - 2025/06/27 07:45:03 - STG2_METERDATA - Executing this pipeline using the Local Pipeline Engine with run configuration 'local'
[2025-06-27T07:45:03.506+0000] {docker.py:436} INFO - 2025/06/27 07:45:03 - STG2_METERDATA - Execution started for pipeline [STG2_METERDATA]
[2025-06-27T07:45:04.250+0000] {docker.py:436} INFO - 2025/06/27 07:45:04 - STG2_METERDATA.0 - Connected to database [POSTGRES_SMART] (commit=1000)
[2025-06-27T07:45:05.904+0000] {docker.py:436} INFO - 2025/06/27 07:45:05 - STG1_METERCODE.0 - Finished reading query, closing connection.
[2025-06-27T07:45:05.908+0000] {docker.py:436} INFO - 2025/06/27 07:45:05 - String operations.0 - Finished processing (I=0, O=0, R=18, W=18, U=0, E=0)
[2025-06-27T07:45:05.914+0000] {docker.py:436} INFO - 2025/06/27 07:45:05 - Replace in string.0 - Finished processing (I=0, O=0, R=18, W=18, U=0, E=0)
[2025-06-27T07:45:06.002+0000] {docker.py:436} INFO - 2025/06/27 07:45:05 - STG1_METERCODE.0 - Finished processing (I=18, O=0, R=0, W=18, U=0, E=0)
[2025-06-27T07:45:06.206+0000] {docker.py:436} INFO - 2025/06/27 07:45:06 - STG2_METERDATA.0 - Finished processing (I=0, O=18, R=18, W=18, U=0, E=0)
[2025-06-27T07:45:06.207+0000] {docker.py:436} INFO - 2025/06/27 07:45:06 - STG2_METERDATA - Pipeline duration : 2.703 seconds [  2.702" ]
[2025-06-27T07:45:06.214+0000] {docker.py:436} INFO - 2025/06/27 07:45:06 - STG2_METERDATA - Execution finished on a local pipeline engine with run configuration 'local'
[2025-06-27T07:45:06.218+0000] {docker.py:436} INFO - 2025/06/27 07:45:06 - WF_METERDATA - Starting action [STG3_METERDATA.hpl]
[2025-06-27T07:45:06.231+0000] {docker.py:436} INFO - 2025/06/27 07:45:06 - STG3_METERDATA.hpl - Using run configuration [local]
[2025-06-27T07:45:06.240+0000] {docker.py:436} INFO - 2025/06/27 07:45:06 - STG3_METERDATA - Executing this pipeline using the Local Pipeline Engine with run configuration 'local'
[2025-06-27T07:45:06.242+0000] {docker.py:436} INFO - 2025/06/27 07:45:06 - STG3_METERDATA - Execution started for pipeline [STG3_METERDATA]
[2025-06-27T07:45:07.024+0000] {docker.py:436} INFO - 2025/06/27 07:45:07 - STG3_METERDATA.0 - Connected to database [POSTGRES_SMART] (commit=1000)
[2025-06-27T07:45:08.446+0000] {docker.py:436} INFO - 2025/06/27 07:45:08 - STG2_METERDATA.0 - Finished reading query, closing connection.
[2025-06-27T07:45:08.451+0000] {docker.py:436} INFO - 2025/06/27 07:45:08 - Select values.0 - Finished processing (I=0, O=0, R=18, W=18, U=0, E=0)
[2025-06-27T07:45:08.550+0000] {docker.py:436} INFO - 2025/06/27 07:45:08 - STG2_METERDATA.0 - Finished processing (I=18, O=0, R=0, W=18, U=0, E=0)
[2025-06-27T07:45:08.758+0000] {docker.py:436} INFO - 2025/06/27 07:45:08 - STG3_METERDATA.0 - Finished processing (I=0, O=18, R=18, W=18, U=0, E=0)
[2025-06-27T07:45:08.759+0000] {docker.py:436} INFO - 2025/06/27 07:45:08 - STG3_METERDATA - Pipeline duration : 2.519 seconds [  2.519" ]
[2025-06-27T07:45:08.767+0000] {docker.py:436} INFO - 2025/06/27 07:45:08 - STG3_METERDATA - ERROR: Error handling writing final pipeline state to location (non-fatal)
[2025-06-27T07:45:08.768+0000] {docker.py:436} INFO - 2025/06/27 07:45:08 - STG3_METERDATA - ERROR: org.apache.hop.core.exception.HopException: 
2025/06/27 07:45:08 - STG3_METERDATA - Error storing execution data
2025/06/27 07:45:08 - STG3_METERDATA - latitud String(2147483647) : There was a data type error: the data type of java.lang.Double object [-12.014781396493674] does not correspond to value meta [String(2147483647)] (through reference chain: org.apache.hop.execution.ExecutionData["rowsBinaryGzipBase64Encoded"])
2025/06/27 07:45:08 - STG3_METERDATA - 
2025/06/27 07:45:08 - STG3_METERDATA - 	at org.apache.hop.execution.local.FileExecutionInfoLocation.registerData(FileExecutionInfoLocation.java:348)
2025/06/27 07:45:08 - STG3_METERDATA - 	at org.apache.hop.pipeline.engines.local.LocalPipelineEngine.stopTransformExecutionInfoTimer(LocalPipelineEngine.java:503)
2025/06/27 07:45:08 - STG3_METERDATA - 	at org.apache.hop.pipeline.engines.local.LocalPipelineEngine.pipelineCompleted(LocalPipelineEngine.java:460)
2025/06/27 07:45:08 - STG3_METERDATA - 	at org.apache.hop.pipeline.Pipeline.fireExecutionFinishedListeners(Pipeline.java:1344)
2025/06/27 07:45:08 - STG3_METERDATA - 	at org.apache.hop.pipeline.Pipeline.lambda$startThreads$0(Pipeline.java:1141)
2025/06/27 07:45:08 - STG3_METERDATA - 	at org.apache.hop.pipeline.transform.BaseTransform.fireTransformFinishedListeners(BaseTransform.java:2840)
2025/06/27 07:45:08 - STG3_METERDATA - 	at org.apache.hop.pipeline.transform.BaseTransform.markStop(BaseTransform.java:2833)
2025/06/27 07:45:08 - STG3_METERDATA - 	at org.apache.hop.pipeline.transform.RunThread.run(RunThread.java:141)
2025/06/27 07:45:08 - STG3_METERDATA - 	at java.base/java.lang.Thread.run(Thread.java:840)
2025/06/27 07:45:08 - STG3_METERDATA - Caused by: com.fasterxml.jackson.databind.JsonMappingException: latitud String(2147483647) : There was a data type error: the data type of java.lang.Double object [-12.014781396493674] does not correspond to value meta [String(2147483647)] (through reference chain: org.apache.hop.execution.ExecutionData["rowsBinaryGzipBase64Encoded"])
2025/06/27 07:45:08 - STG3_METERDATA - 	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:402)
2025/06/27 07:45:08 - STG3_METERDATA - 	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:361)
2025/06/27 07:45:08 - STG3_METERDATA - 	at com.fasterxml.jackson.databind.ser.std.StdSerializer.wrapAndThrow(StdSerializer.java:323)
2025/06/27 07:45:08 - STG3_METERDATA - 	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:780)
2025/06/27 07:45:08 - STG3_METERDATA - 	at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:178)
2025/06/27 07:45:08 - STG3_METERDATA - 	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider._serialize(DefaultSerializerProvider.java:479)
2025/06/27 07:45:08 - STG3_METERDATA - 	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:318)
2025/06/27 07:45:08 - STG3_METERDATA - 	at com.fasterxml.jackson.databind.ObjectWriter$Prefetch.serialize(ObjectWriter.java:1572)
2025/06/27 07:45:08 - STG3_METERDATA - 	at com.fasterxml.jackson.databind.ObjectWriter._writeValueAndClose(ObjectWriter.java:1273)
2025/06/27 07:45:08 - STG3_METERDATA - 	at com.fasterxml.jackson.databind.ObjectWriter.writeValue(ObjectWriter.java:1098)
2025/06/27 07:45:08 - STG3_METERDATA - 	at org.apache.hop.execution.local.FileExecutionInfoLocation.registerData(FileExecutionInfoLocation.java:345)
2025/06/27 07:45:08 - STG3_METERDATA - 	... 8 more
2025/06/27 07:45:08 - STG3_METERDATA - Caused by: java.lang.RuntimeException: latitud String(2147483647) : There was a data type error: the data type of java.lang.Double object [-12.014781396493674] does not correspond to value meta [String(2147483647)]
2025/06/27 07:45:08 - STG3_METERDATA - 	at org.apache.hop.core.row.value.ValueMetaBase.writeData(ValueMetaBase.java:3457)
2025/06/27 07:45:08 - STG3_METERDATA - 	at org.apache.hop.core.row.RowMeta.writeData(RowMeta.java:719)
2025/06/27 07:45:08 - STG3_METERDATA - 	at org.apache.hop.execution.ExecutionData.getRowsBinaryGzipBase64Encoded(ExecutionData.java:193)
2025/06/27 07:45:08 - STG3_METERDATA - 	at jdk.internal.reflect.GeneratedMethodAccessor99.invoke(Unknown Source)
2025/06/27 07:45:08 - STG3_METERDATA - 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2025/06/27 07:45:08 - STG3_METERDATA - 	at java.base/java.lang.reflect.Method.invoke(Method.java:569)
2025/06/27 07:45:08 - STG3_METERDATA - 	at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:688)
2025/06/27 07:45:08 - STG3_METERDATA - 	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:772)
2025/06/27 07:45:08 - STG3_METERDATA - 	... 15 more
2025/06/27 07:45:08 - STG3_METERDATA - Execution finished on a local pipeline engine with run configuration 'local'
[2025-06-27T07:45:08.770+0000] {docker.py:436} INFO - 2025/06/27 07:45:08 - WF_METERDATA - Starting action [FINAL_METERDATA.hpl]
[2025-06-27T07:45:08.793+0000] {docker.py:436} INFO - 2025/06/27 07:45:08 - FINAL_METERDATA.hpl - Using run configuration [local]
[2025-06-27T07:45:08.804+0000] {docker.py:436} INFO - 2025/06/27 07:45:08 - FINAL_METERDATA - Executing this pipeline using the Local Pipeline Engine with run configuration 'local'
[2025-06-27T07:45:08.806+0000] {docker.py:436} INFO - 2025/06/27 07:45:08 - FINAL_METERDATA - Execution started for pipeline [FINAL_METERDATA]
[2025-06-27T07:45:10.049+0000] {docker.py:436} INFO - 2025/06/27 07:45:10 - stg3_meterdata to final_meterdata.0 - Finished reading query, closing connection.
[2025-06-27T07:45:10.051+0000] {docker.py:436} INFO - 2025/06/27 07:45:10 - stg3_meterdata to final_meterdata.0 - Finished processing (I=0, O=0, R=0, W=1, U=0, E=0)
[2025-06-27T07:45:10.052+0000] {docker.py:436} INFO - 2025/06/27 07:45:10 - FINAL_METERDATA - Pipeline duration : 1.246 seconds [  1.246" ]
[2025-06-27T07:45:10.055+0000] {docker.py:436} INFO - 2025/06/27 07:45:10 - FINAL_METERDATA - Execution finished on a local pipeline engine with run configuration 'local'
[2025-06-27T07:45:10.058+0000] {docker.py:436} INFO - 2025/06/27 07:45:10 - WF_METERDATA - Starting action [End Repeat]
[2025-06-27T07:45:10.064+0000] {docker.py:436} INFO - 2025/06/27 07:45:10 - WF_METERDATA - Finished action [End Repeat] (result=[true])
2025/06/27 07:45:10 - WF_METERDATA - Finished action [FINAL_METERDATA.hpl] (result=[true])
[2025-06-27T07:45:10.065+0000] {docker.py:436} INFO - 2025/06/27 07:45:10 - WF_METERDATA - Finished action [STG3_METERDATA.hpl] (result=[true])
2025/06/27 07:45:10 - WF_METERDATA - Finished action [STG2_METERDATA.hpl] (result=[true])
[2025-06-27T07:45:10.066+0000] {docker.py:436} INFO - 2025/06/27 07:45:10 - WF_METERDATA - Finished action [STG1_METERDATA.hpl] (result=[true])
[2025-06-27T07:45:10.067+0000] {docker.py:436} INFO - 2025/06/27 07:45:10 - WF_METERDATA - Workflow execution finished
[2025-06-27T07:45:10.070+0000] {docker.py:436} INFO - 2025/06/27 07:45:10 - WF_METERDATA - Workflow duration : 8.522 seconds [  8.522" ]
[2025-06-27T07:45:10.072+0000] {docker.py:436} INFO - 2025/06/27 07:45:10 - WF_MEDIDORES - Starting action [STG5_MEDIDORES.hpl]
[2025-06-27T07:45:10.094+0000] {docker.py:436} INFO - 2025/06/27 07:45:10 - STG5_MEDIDORES.hpl - Using run configuration [local]
[2025-06-27T07:45:10.107+0000] {docker.py:436} INFO - 2025/06/27 07:45:10 - STG5_MEDIDORES - Executing this pipeline using the Local Pipeline Engine with run configuration 'local'
[2025-06-27T07:45:10.109+0000] {docker.py:436} INFO - 2025/06/27 07:45:10 - STG5_MEDIDORES - Execution started for pipeline [STG5_MEDIDORES]
[2025-06-27T07:45:10.884+0000] {docker.py:436} INFO - 2025/06/27 07:45:10 - STG5_MEDIDORES.0 - Connected to database [POSTGRES_SMART] (commit=1000)
[2025-06-27T07:45:13.309+0000] {docker.py:436} INFO - 2025/06/27 07:45:13 - STG3_METERDATA.0 - Finished reading query, closing connection.
[2025-06-27T07:45:13.315+0000] {docker.py:436} INFO - 2025/06/27 07:45:13 - Replace in string.0 - Finished processing (I=0, O=0, R=16398, W=16398, U=0, E=0)
[2025-06-27T07:45:13.407+0000] {docker.py:436} INFO - 2025/06/27 07:45:13 - STG3_METERDATA.0 - Finished processing (I=16398, O=0, R=0, W=16398, U=0, E=0)
[2025-06-27T07:45:16.436+0000] {docker.py:436} INFO - 2025/06/27 07:45:16 - String operations.0 - Finished processing (I=0, O=0, R=16398, W=16398, U=0, E=0)
[2025-06-27T07:45:21.900+0000] {docker.py:436} INFO - 2025/06/27 07:45:21 - STG5_MEDIDORES.0 - Finished processing (I=0, O=16398, R=16398, W=16398, U=0, E=0)
[2025-06-27T07:45:21.902+0000] {docker.py:436} INFO - 2025/06/27 07:45:21 - STG5_MEDIDORES - Pipeline duration : 11.791 seconds [ 11.791" ]
[2025-06-27T07:45:21.931+0000] {docker.py:436} INFO - 2025/06/27 07:45:21 - STG5_MEDIDORES - Execution finished on a local pipeline engine with run configuration 'local'
[2025-06-27T07:45:21.933+0000] {docker.py:436} INFO - 2025/06/27 07:45:21 - WF_MEDIDORES - Starting action [STG6_MEDIDORES.hpl]
[2025-06-27T07:45:21.950+0000] {docker.py:436} INFO - 2025/06/27 07:45:21 - STG6_MEDIDORES.hpl - Using run configuration [local]
[2025-06-27T07:45:21.960+0000] {docker.py:436} INFO - 2025/06/27 07:45:21 - STG6_MEDIDORES - Executing this pipeline using the Local Pipeline Engine with run configuration 'local'
[2025-06-27T07:45:21.963+0000] {docker.py:436} INFO - 2025/06/27 07:45:21 - STG6_MEDIDORES - Execution started for pipeline [STG6_MEDIDORES]
[2025-06-27T07:45:22.700+0000] {docker.py:436} INFO - 2025/06/27 07:45:22 - Table output.0 - Connected to database [POSTGRES_SMART] (commit=1000)
[2025-06-27T07:45:28.336+0000] {docker.py:436} INFO - 2025/06/27 07:45:28 - STG5_MEDIDORES.0 - Finished reading query, closing connection.
[2025-06-27T07:45:28.437+0000] {docker.py:436} INFO - 2025/06/27 07:45:28 - STG5_MEDIDORES.0 - Finished processing (I=16385, O=0, R=0, W=16385, U=0, E=0)
[2025-06-27T07:45:33.717+0000] {docker.py:436} INFO - 2025/06/27 07:45:33 - Table output.0 - Finished processing (I=0, O=16385, R=16385, W=16385, U=0, E=0)
[2025-06-27T07:45:33.718+0000] {docker.py:436} INFO - 2025/06/27 07:45:33 - STG6_MEDIDORES - Pipeline duration : 11.758 seconds [ 11.757" ]
[2025-06-27T07:45:33.729+0000] {docker.py:436} INFO - 2025/06/27 07:45:33 - STG6_MEDIDORES - Execution finished on a local pipeline engine with run configuration 'local'
[2025-06-27T07:45:33.731+0000] {docker.py:436} INFO - 2025/06/27 07:45:33 - WF_MEDIDORES - Starting action [End Repeat]
[2025-06-27T07:45:33.737+0000] {docker.py:436} INFO - 2025/06/27 07:45:33 - WF_MEDIDORES - Finished action [End Repeat] (result=[true])
2025/06/27 07:45:33 - WF_MEDIDORES - Finished action [STG6_MEDIDORES.hpl] (result=[true])
2025/06/27 07:45:33 - WF_MEDIDORES - Finished action [STG5_MEDIDORES.hpl] (result=[true])
2025/06/27 07:45:33 - WF_MEDIDORES - Finished action [WF_METERDATA.hwf] (result=[true])
[2025-06-27T07:45:33.738+0000] {docker.py:436} INFO - 2025/06/27 07:45:33 - WF_MEDIDORES - Finished action [STG4_MEDIDORES.hpl] (result=[true])
2025/06/27 07:45:33 - WF_MEDIDORES - Finished action [STG3_MEDIDORES.hpl] (result=[true])
[2025-06-27T07:45:33.738+0000] {docker.py:436} INFO - 2025/06/27 07:45:33 - WF_MEDIDORES - Finished action [STG2_MEDIDORES.hpl] (result=[true])
[2025-06-27T07:45:33.739+0000] {docker.py:436} INFO - 2025/06/27 07:45:33 - WF_MEDIDORES - Finished action [STG1_MEDIDORES.hpl] (result=[true])
2025/06/27 07:45:33 - WF_MEDIDORES - Workflow execution finished
[2025-06-27T07:45:33.741+0000] {docker.py:436} INFO - 2025/06/27 07:45:33 - WF_MEDIDORES - Workflow duration : 101.864 seconds [  1' 41.864" ]
[2025-06-27T07:45:33.744+0000] {docker.py:436} INFO - 2025/06/27 07:45:33 - WF_MAIN_END_MONTH - Starting action [STG1_HECHOS.hpl]
[2025-06-27T07:45:33.761+0000] {docker.py:436} INFO - 2025/06/27 07:45:33 - STG1_HECHOS.hpl - Using run configuration [local]
[2025-06-27T07:45:33.771+0000] {docker.py:436} INFO - 2025/06/27 07:45:33 - STG1_HECHOS - Executing this pipeline using the Local Pipeline Engine with run configuration 'local'
[2025-06-27T07:45:33.772+0000] {docker.py:436} INFO - 2025/06/27 07:45:33 - STG1_HECHOS - Execution started for pipeline [STG1_HECHOS]
[2025-06-27T07:45:43.814+0000] {docker.py:436} INFO - 2025/06/27 07:45:43 - STG1_HECHOS.0 - ERROR: An error occurred initializing this transform: 
2025/06/27 07:45:43 - STG1_HECHOS.0 - Error occurred while trying to connect to the database
2025/06/27 07:45:43 - STG1_HECHOS.0 - 
2025/06/27 07:45:43 - STG1_HECHOS.0 - Error connecting to database: (using class org.postgresql.Driver)
2025/06/27 07:45:43 - STG1_HECHOS.0 - The connection attempt failed.
[2025-06-27T07:45:43.816+0000] {docker.py:436} INFO - 2025/06/27 07:45:43 - STG1_HECHOS.0 - ERROR: Error initializing transform [STG1_HECHOS]
[2025-06-27T07:45:43.817+0000] {docker.py:436} INFO - 2025/06/27 07:45:43 - STG1_HECHOS - ERROR: Transform [STG1_HECHOS.0] failed to initialize!
[2025-06-27T07:45:43.818+0000] {docker.py:436} INFO - 2025/06/27 07:45:43 - STG1_HECHOS.0 - ERROR: Unexpected error rolling back the database connection.
[2025-06-27T07:45:43.819+0000] {docker.py:436} INFO - 2025/06/27 07:45:43 - STG1_HECHOS.0 - ERROR: org.apache.hop.core.exception.HopDatabaseException: 
2025/06/27 07:45:43 - STG1_HECHOS.0 - Unable to get database metadata from this database connection
2025/06/27 07:45:43 - STG1_HECHOS.0 - 
2025/06/27 07:45:43 - STG1_HECHOS.0 - Error connecting to database [***]
2025/06/27 07:45:43 - STG1_HECHOS.0 - 
2025/06/27 07:45:43 - STG1_HECHOS.0 - 
2025/06/27 07:45:43 - STG1_HECHOS.0 - 	at org.apache.hop.core.database.Database.getDatabaseMetaData(Database.java:2897)
2025/06/27 07:45:43 - STG1_HECHOS.0 - 	at org.apache.hop.core.database.Database.rollback(Database.java:737)
2025/06/27 07:45:43 - STG1_HECHOS.0 - 	at org.apache.hop.core.database.Database.rollback(Database.java:729)
2025/06/27 07:45:43 - STG1_HECHOS.0 - 	at org.apache.hop.pipeline.transforms.tableoutput.TableOutput.emptyAndCommitBatchBuffers(TableOutput.java:648)
2025/06/27 07:45:43 - STG1_HECHOS.0 - 	at org.apache.hop.pipeline.transforms.tableoutput.TableOutput.dispose(TableOutput.java:568)
2025/06/27 07:45:43 - STG1_HECHOS.0 - 	at org.apache.hop.pipeline.Pipeline.prepareExecution(Pipeline.java:1056)
2025/06/27 07:45:43 - STG1_HECHOS.0 - 	at org.apache.hop.pipeline.engines.local.LocalPipelineEngine.prepareExecution(LocalPipelineEngine.java:232)
2025/06/27 07:45:43 - STG1_HECHOS.0 - 	at org.apache.hop.pipeline.Pipeline.execute(Pipeline.java:528)
2025/06/27 07:45:43 - STG1_HECHOS.0 - 	at org.apache.hop.workflow.actions.pipeline.ActionPipeline.execute(ActionPipeline.java:543)
2025/06/27 07:45:43 - STG1_HECHOS.0 - 	at org.apache.hop.workflow.Workflow.executeFromStart(Workflow.java:751)
2025/06/27 07:45:43 - STG1_HECHOS.0 - 	at org.apache.hop.workflow.Workflow.executeFromStart(Workflow.java:902)
2025/06/27 07:45:43 - STG1_HECHOS.0 - 	at org.apache.hop.workflow.Workflow.executeFromStart(Workflow.java:902)
2025/06/27 07:45:43 - STG1_HECHOS.0 - 	at org.apache.hop.workflow.Workflow.executeFromStart(Workflow.java:902)
2025/06/27 07:45:43 - STG1_HECHOS.0 - 	at org.apache.hop.workflow.Workflow.executeFromStart(Workflow.java:902)
2025/06/27 07:45:43 - STG1_HECHOS.0 - 	at org.apache.hop.workflow.Workflow.executeFromStart(Workflow.java:453)
2025/06/27 07:45:43 - STG1_HECHOS.0 - 	at org.apache.hop.workflow.Workflow.startExecution(Workflow.java:313)
2025/06/27 07:45:43 - STG1_HECHOS.0 - 	at org.apache.hop.workflow.engines.local.LocalWorkflowEngine.startExecution(LocalWorkflowEngine.java:249)
2025/06/27 07:45:43 - STG1_HECHOS.0 - 	at org.apache.hop.run.HopRun.runWorkflow(HopRun.java:438)
2025/06/27 07:45:43 - STG1_HECHOS.0 - 	at org.apache.hop.run.HopRun.runWorkflow(HopRun.java:389)
2025/06/27 07:45:43 - STG1_HECHOS.0 - 	at org.apache.hop.run.HopRun.run(HopRun.java:206)
2025/06/27 07:45:43 - STG1_HECHOS.0 - 	at org.apache.hop.run.HopRun.main(HopRun.java:931)
2025/06/27 07:45:43 - STG1_HECHOS.0 - Caused by: org.apache.hop.core.exception.HopDatabaseException: 
2025/06/27 07:45:43 - STG1_HECHOS.0 - Error connecting to database [***]
2025/06/27 07:45:43 - STG1_HECHOS.0 - 
2025/06/27 07:45:43 - STG1_HECHOS.0 - 	at org.apache.hop.core.database.Database.getDatabaseMetaData(Database.java:2890)
2025/06/27 07:45:43 - STG1_HECHOS.0 - 	... 20 more
2025/06/27 07:45:43 - STG1_HECHOS.hpl - ERROR: Unable to prepare for execution of the pipeline
[2025-06-27T07:45:43.820+0000] {docker.py:436} INFO - 2025/06/27 07:45:43 - STG1_HECHOS.hpl - ERROR: org.apache.hop.core.exception.HopException: 
2025/06/27 07:45:43 - STG1_HECHOS.hpl - We failed to initialize at least one transform.  Execution can not begin!
2025/06/27 07:45:43 - STG1_HECHOS.hpl - 
2025/06/27 07:45:43 - STG1_HECHOS.hpl - 
2025/06/27 07:45:43 - STG1_HECHOS.hpl - 	at org.apache.hop.pipeline.Pipeline.prepareExecution(Pipeline.java:1088)
2025/06/27 07:45:43 - STG1_HECHOS.hpl - 	at org.apache.hop.pipeline.engines.local.LocalPipelineEngine.prepareExecution(LocalPipelineEngine.java:232)
2025/06/27 07:45:43 - STG1_HECHOS.hpl - 	at org.apache.hop.pipeline.Pipeline.execute(Pipeline.java:528)
2025/06/27 07:45:43 - STG1_HECHOS.hpl - 	at org.apache.hop.workflow.actions.pipeline.ActionPipeline.execute(ActionPipeline.java:543)
2025/06/27 07:45:43 - STG1_HECHOS.hpl - 	at org.apache.hop.workflow.Workflow.executeFromStart(Workflow.java:751)
2025/06/27 07:45:43 - STG1_HECHOS.hpl - 	at org.apache.hop.workflow.Workflow.executeFromStart(Workflow.java:902)
2025/06/27 07:45:43 - STG1_HECHOS.hpl - 	at org.apache.hop.workflow.Workflow.executeFromStart(Workflow.java:902)
2025/06/27 07:45:43 - STG1_HECHOS.hpl - 	at org.apache.hop.workflow.Workflow.executeFromStart(Workflow.java:902)
2025/06/27 07:45:43 - STG1_HECHOS.hpl - 	at org.apache.hop.workflow.Workflow.executeFromStart(Workflow.java:902)
2025/06/27 07:45:43 - STG1_HECHOS.hpl - 	at org.apache.hop.workflow.Workflow.executeFromStart(Workflow.java:453)
2025/06/27 07:45:43 - STG1_HECHOS.hpl - 	at org.apache.hop.workflow.Workflow.startExecution(Workflow.java:313)
2025/06/27 07:45:43 - STG1_HECHOS.hpl - 	at org.apache.hop.workflow.engines.local.LocalWorkflowEngine.startExecution(LocalWorkflowEngine.java:249)
2025/06/27 07:45:43 - STG1_HECHOS.hpl - 	at org.apache.hop.run.HopRun.runWorkflow(HopRun.java:438)
2025/06/27 07:45:43 - STG1_HECHOS.hpl - 	at org.apache.hop.run.HopRun.runWorkflow(HopRun.java:389)
2025/06/27 07:45:43 - STG1_HECHOS.hpl - 	at org.apache.hop.run.HopRun.run(HopRun.java:206)
2025/06/27 07:45:43 - STG1_HECHOS.hpl - 	at org.apache.hop.run.HopRun.main(HopRun.java:931)
[2025-06-27T07:45:43.821+0000] {docker.py:436} INFO - 2025/06/27 07:45:43 - WF_MAIN_END_MONTH - Finished action [STG1_HECHOS.hpl] (result=[false])
2025/06/27 07:45:43 - WF_MAIN_END_MONTH - Finished action [WF_MEDIDORES.hwf] (result=[false])
2025/06/27 07:45:43 - WF_MAIN_END_MONTH - Starting action [STG1_ALARMAS.hpl]
[2025-06-27T07:45:43.839+0000] {docker.py:436} INFO - 2025/06/27 07:45:43 - STG1_ALARMAS.hpl - Using run configuration [local]
[2025-06-27T07:45:43.850+0000] {docker.py:436} INFO - 2025/06/27 07:45:43 - STG1_ALARMAS - Executing this pipeline using the Local Pipeline Engine with run configuration 'local'
[2025-06-27T07:45:43.852+0000] {docker.py:436} INFO - 2025/06/27 07:45:43 - STG1_ALARMAS - Execution started for pipeline [STG1_ALARMAS]
[2025-06-27T07:45:44.601+0000] {docker.py:436} INFO - 2025/06/27 07:45:44 - Table output.0 - Connected to database [POSTGRES_SMART] (commit=1000)
[2025-06-27T07:45:44.879+0000] {docker.py:436} INFO - 2025/06/27 07:45:44 - CSV_ALARMAS.0 - Header row skipped in file '/files/FuentesSmartMed/alarmas.csv'
